
namespace Final_project
{
    partial class AULAS_FORM
    {
        /// <summary>
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary>
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

        /// <summary>
        /// Required method for Designer support - do not modify
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(AULAS_FORM));
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties1 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties2 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties3 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties4 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            System.Windows.Forms.DataGridViewCellStyle dataGridViewCellStyle1 = new System.Windows.Forms.DataGridViewCellStyle();
            System.Windows.Forms.DataGridViewCellStyle dataGridViewCellStyle2 = new System.Windows.Forms.DataGridViewCellStyle();
            System.Windows.Forms.DataGridViewCellStyle dataGridViewCellStyle3 = new System.Windows.Forms.DataGridViewCellStyle();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges1 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges2 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges3 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges4 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties5 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties6 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties7 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties8 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties9 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties10 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties11 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties12 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties13 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties14 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties15 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties16 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            this.bunifuPanel1 = new Bunifu.UI.WinForms.BunifuPanel();
            this.bunifuPictureBox1 = new Bunifu.UI.WinForms.BunifuPictureBox();
            this.bunifuLabel1 = new Bunifu.UI.WinForms.BunifuLabel();
            this.buscar = new Bunifu.UI.WinForms.BunifuTextBox();
            this.bunifuPictureBox2 = new Bunifu.UI.WinForms.BunifuPictureBox();
            this.tabla = new Bunifu.UI.WinForms.BunifuDataGridView();
            this.btn_nuevo = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.btn_editar = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.btn_eliminar = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.btn_guardar = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.buscarcod = new Bunifu.UI.WinForms.BunifuTextBox();
            this.buscaraula = new Bunifu.UI.WinForms.BunifuTextBox();
            this.buscaredificio = new Bunifu.UI.WinForms.BunifuTextBox();
            this.bunifuLabel2 = new Bunifu.UI.WinForms.BunifuLabel();
            this.bunifuLabel3 = new Bunifu.UI.WinForms.BunifuLabel();
            this.bunifuLabel4 = new Bunifu.UI.WinForms.BunifuLabel();
            this.bunifuPanel1.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)(this.bunifuPictureBox1)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.bunifuPictureBox2)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.tabla)).BeginInit();
            this.SuspendLayout();
            // 
            // bunifuPanel1
            // 
            this.bunifuPanel1.BackgroundColor = System.Drawing.Color.FromArgb(((int)(((byte)(228)))), ((int)(((byte)(37)))), ((int)(((byte)(43)))));
            this.bunifuPanel1.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("bunifuPanel1.BackgroundImage")));
            this.bunifuPanel1.BackgroundImageLayout = System.Windows.Forms.ImageLayout.Stretch;
            this.bunifuPanel1.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(228)))), ((int)(((byte)(37)))), ((int)(((byte)(43)))));
            this.bunifuPanel1.BorderRadius = 3;
            this.bunifuPanel1.BorderThickness = 1;
            this.bunifuPanel1.Controls.Add(this.bunifuLabel1);
            this.bunifuPanel1.Controls.Add(this.bunifuPictureBox1);
            this.bunifuPanel1.Dock = System.Windows.Forms.DockStyle.Top;
            this.bunifuPanel1.Location = new System.Drawing.Point(0, 0);
            this.bunifuPanel1.Name = "bunifuPanel1";
            this.bunifuPanel1.ShowBorders = true;
            this.bunifuPanel1.Size = new System.Drawing.Size(922, 67);
            this.bunifuPanel1.TabIndex = 0;
            // 
            // bunifuPictureBox1
            // 
            this.bunifuPictureBox1.AllowFocused = false;
            this.bunifuPictureBox1.Anchor = System.Windows.Forms.AnchorStyles.None;
            this.bunifuPictureBox1.AutoSizeHeight = false;
            this.bunifuPictureBox1.BorderRadius = 0;
            this.bunifuPictureBox1.Image = global::Final_project.Properties.Resources.itla_logo;
            this.bunifuPictureBox1.IsCircle = false;
            this.bunifuPictureBox1.Location = new System.Drawing.Point(3, 3);
            this.bunifuPictureBox1.Name = "bunifuPictureBox1";
            this.bunifuPictureBox1.Size = new System.Drawing.Size(165, 61);
            this.bunifuPictureBox1.SizeMode = System.Windows.Forms.PictureBoxSizeMode.Zoom;
            this.bunifuPictureBox1.TabIndex = 5;
            this.bunifuPictureBox1.TabStop = false;
            this.bunifuPictureBox1.Type = Bunifu.UI.WinForms.BunifuPictureBox.Types.Custom;
            // 
            // bunifuLabel1
            // 
            this.bunifuLabel1.AllowParentOverrides = false;
            this.bunifuLabel1.AutoEllipsis = false;
            this.bunifuLabel1.Cursor = System.Windows.Forms.Cursors.Default;
            this.bunifuLabel1.CursorType = System.Windows.Forms.Cursors.Default;
            this.bunifuLabel1.Font = new System.Drawing.Font("Lucida Fax", 24F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.bunifuLabel1.Location = new System.Drawing.Point(174, 12);
            this.bunifuLabel1.Name = "bunifuLabel1";
            this.bunifuLabel1.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.bunifuLabel1.Size = new System.Drawing.Size(105, 37);
            this.bunifuLabel1.TabIndex = 1;
            this.bunifuLabel1.Text = "AULAS";
            this.bunifuLabel1.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.bunifuLabel1.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // buscar
            // 
            this.buscar.AcceptsReturn = false;
            this.buscar.AcceptsTab = false;
            this.buscar.AnimationSpeed = 200;
            this.buscar.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.buscar.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.buscar.AutoSizeHeight = true;
            this.buscar.BackColor = System.Drawing.Color.White;
            this.buscar.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("buscar.BackgroundImage")));
            this.buscar.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.buscar.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.buscar.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.buscar.BorderColorIdle = System.Drawing.Color.Silver;
            this.buscar.BorderRadius = 1;
            this.buscar.BorderThickness = 1;
            this.buscar.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.buscar.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.buscar.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.buscar.DefaultText = "";
            this.buscar.FillColor = System.Drawing.Color.White;
            this.buscar.HideSelection = true;
            this.buscar.IconLeft = null;
            this.buscar.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.buscar.IconPadding = 10;
            this.buscar.IconRight = null;
            this.buscar.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.buscar.Lines = new string[0];
            this.buscar.Location = new System.Drawing.Point(614, 125);
            this.buscar.MaxLength = 32767;
            this.buscar.MinimumSize = new System.Drawing.Size(1, 1);
            this.buscar.Modified = false;
            this.buscar.Multiline = false;
            this.buscar.Name = "buscar";
            stateProperties1.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties1.FillColor = System.Drawing.Color.Empty;
            stateProperties1.ForeColor = System.Drawing.Color.Empty;
            stateProperties1.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.buscar.OnActiveState = stateProperties1;
            stateProperties2.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties2.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties2.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties2.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.buscar.OnDisabledState = stateProperties2;
            stateProperties3.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties3.FillColor = System.Drawing.Color.Empty;
            stateProperties3.ForeColor = System.Drawing.Color.Empty;
            stateProperties3.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.buscar.OnHoverState = stateProperties3;
            stateProperties4.BorderColor = System.Drawing.Color.Silver;
            stateProperties4.FillColor = System.Drawing.Color.White;
            stateProperties4.ForeColor = System.Drawing.Color.Empty;
            stateProperties4.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.buscar.OnIdleState = stateProperties4;
            this.buscar.Padding = new System.Windows.Forms.Padding(3);
            this.buscar.PasswordChar = '\0';
            this.buscar.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.buscar.PlaceholderText = "Enter text";
            this.buscar.ReadOnly = false;
            this.buscar.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.buscar.SelectedText = "";
            this.buscar.SelectionLength = 0;
            this.buscar.SelectionStart = 0;
            this.buscar.ShortcutsEnabled = true;
            this.buscar.Size = new System.Drawing.Size(260, 57);
            this.buscar.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Material;
            this.buscar.TabIndex = 1;
            this.buscar.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.buscar.TextMarginBottom = 0;
            this.buscar.TextMarginLeft = 3;
            this.buscar.TextMarginTop = 1;
            this.buscar.TextPlaceholder = "Enter text";
            this.buscar.UseSystemPasswordChar = false;
            this.buscar.WordWrap = true;
            this.buscar.TextChanged += new System.EventHandler(this.buscar_TextChanged);
            // 
            // bunifuPictureBox2
            // 
            this.bunifuPictureBox2.AllowFocused = false;
            this.bunifuPictureBox2.Anchor = System.Windows.Forms.AnchorStyles.None;
            this.bunifuPictureBox2.AutoSizeHeight = false;
            this.bunifuPictureBox2.BorderRadius = 0;
            this.bunifuPictureBox2.Image = global::Final_project.Properties.Resources.searchmagnifierinterfacesymbol1_79893;
            this.bunifuPictureBox2.IsCircle = false;
            this.bunifuPictureBox2.Location = new System.Drawing.Point(614, 80);
            this.bunifuPictureBox2.Name = "bunifuPictureBox2";
            this.bunifuPictureBox2.Size = new System.Drawing.Size(43, 39);
            this.bunifuPictureBox2.SizeMode = System.Windows.Forms.PictureBoxSizeMode.Zoom;
            this.bunifuPictureBox2.TabIndex = 2;
            this.bunifuPictureBox2.TabStop = false;
            this.bunifuPictureBox2.Type = Bunifu.UI.WinForms.BunifuPictureBox.Types.Custom;
            // 
            // tabla
            // 
            this.tabla.AllowCustomTheming = false;
            this.tabla.AllowUserToDeleteRows = false;
            dataGridViewCellStyle1.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(44)))), ((int)(((byte)(48)))), ((int)(((byte)(52)))));
            dataGridViewCellStyle1.ForeColor = System.Drawing.Color.White;
            this.tabla.AlternatingRowsDefaultCellStyle = dataGridViewCellStyle1;
            this.tabla.AutoSizeColumnsMode = System.Windows.Forms.DataGridViewAutoSizeColumnsMode.Fill;
            this.tabla.BorderStyle = System.Windows.Forms.BorderStyle.None;
            this.tabla.CellBorderStyle = System.Windows.Forms.DataGridViewCellBorderStyle.SingleHorizontal;
            this.tabla.ColumnHeadersBorderStyle = System.Windows.Forms.DataGridViewHeaderBorderStyle.None;
            dataGridViewCellStyle2.Alignment = System.Windows.Forms.DataGridViewContentAlignment.MiddleLeft;
            dataGridViewCellStyle2.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(15)))), ((int)(((byte)(16)))), ((int)(((byte)(18)))));
            dataGridViewCellStyle2.Font = new System.Drawing.Font("Segoe UI Semibold", 11.75F, System.Drawing.FontStyle.Bold);
            dataGridViewCellStyle2.ForeColor = System.Drawing.Color.White;
            dataGridViewCellStyle2.SelectionBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(63)))), ((int)(((byte)(63)))), ((int)(((byte)(65)))));
            dataGridViewCellStyle2.SelectionForeColor = System.Drawing.Color.White;
            dataGridViewCellStyle2.WrapMode = System.Windows.Forms.DataGridViewTriState.True;
            this.tabla.ColumnHeadersDefaultCellStyle = dataGridViewCellStyle2;
            this.tabla.ColumnHeadersHeight = 40;
            this.tabla.CurrentTheme.AlternatingRowsStyle.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(44)))), ((int)(((byte)(48)))), ((int)(((byte)(52)))));
            this.tabla.CurrentTheme.AlternatingRowsStyle.Font = new System.Drawing.Font("Segoe UI Semibold", 9.75F, System.Drawing.FontStyle.Bold);
            this.tabla.CurrentTheme.AlternatingRowsStyle.ForeColor = System.Drawing.Color.White;
            this.tabla.CurrentTheme.AlternatingRowsStyle.SelectionBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(114)))), ((int)(((byte)(117)))), ((int)(((byte)(119)))));
            this.tabla.CurrentTheme.AlternatingRowsStyle.SelectionForeColor = System.Drawing.Color.WhiteSmoke;
            this.tabla.CurrentTheme.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(15)))), ((int)(((byte)(16)))), ((int)(((byte)(18)))));
            this.tabla.CurrentTheme.GridColor = System.Drawing.Color.FromArgb(((int)(((byte)(50)))), ((int)(((byte)(56)))), ((int)(((byte)(62)))));
            this.tabla.CurrentTheme.HeaderStyle.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(15)))), ((int)(((byte)(16)))), ((int)(((byte)(18)))));
            this.tabla.CurrentTheme.HeaderStyle.Font = new System.Drawing.Font("Segoe UI Semibold", 11.75F, System.Drawing.FontStyle.Bold);
            this.tabla.CurrentTheme.HeaderStyle.ForeColor = System.Drawing.Color.White;
            this.tabla.CurrentTheme.HeaderStyle.SelectionBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(63)))), ((int)(((byte)(63)))), ((int)(((byte)(65)))));
            this.tabla.CurrentTheme.HeaderStyle.SelectionForeColor = System.Drawing.Color.White;
            this.tabla.CurrentTheme.Name = null;
            this.tabla.CurrentTheme.RowsStyle.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(33)))), ((int)(((byte)(37)))), ((int)(((byte)(41)))));
            this.tabla.CurrentTheme.RowsStyle.Font = new System.Drawing.Font("Segoe UI Semibold", 9.75F, System.Drawing.FontStyle.Bold);
            this.tabla.CurrentTheme.RowsStyle.ForeColor = System.Drawing.Color.White;
            this.tabla.CurrentTheme.RowsStyle.SelectionBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(114)))), ((int)(((byte)(117)))), ((int)(((byte)(119)))));
            this.tabla.CurrentTheme.RowsStyle.SelectionForeColor = System.Drawing.Color.WhiteSmoke;
            dataGridViewCellStyle3.Alignment = System.Windows.Forms.DataGridViewContentAlignment.MiddleLeft;
            dataGridViewCellStyle3.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(33)))), ((int)(((byte)(37)))), ((int)(((byte)(41)))));
            dataGridViewCellStyle3.Font = new System.Drawing.Font("Segoe UI Semibold", 9.75F, System.Drawing.FontStyle.Bold);
            dataGridViewCellStyle3.ForeColor = System.Drawing.Color.White;
            dataGridViewCellStyle3.SelectionBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(114)))), ((int)(((byte)(117)))), ((int)(((byte)(119)))));
            dataGridViewCellStyle3.SelectionForeColor = System.Drawing.Color.WhiteSmoke;
            dataGridViewCellStyle3.WrapMode = System.Windows.Forms.DataGridViewTriState.False;
            this.tabla.DefaultCellStyle = dataGridViewCellStyle3;
            this.tabla.EnableHeadersVisualStyles = false;
            this.tabla.GridColor = System.Drawing.Color.FromArgb(((int)(((byte)(50)))), ((int)(((byte)(56)))), ((int)(((byte)(62)))));
            this.tabla.HeaderBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(15)))), ((int)(((byte)(16)))), ((int)(((byte)(18)))));
            this.tabla.HeaderBgColor = System.Drawing.Color.Empty;
            this.tabla.HeaderForeColor = System.Drawing.Color.White;
            this.tabla.Location = new System.Drawing.Point(12, 94);
            this.tabla.Name = "tabla";
            this.tabla.ReadOnly = true;
            this.tabla.RowHeadersVisible = false;
            this.tabla.RowTemplate.Height = 40;
            this.tabla.SelectionMode = System.Windows.Forms.DataGridViewSelectionMode.FullRowSelect;
            this.tabla.Size = new System.Drawing.Size(559, 423);
            this.tabla.TabIndex = 3;
            this.tabla.Theme = Bunifu.UI.WinForms.BunifuDataGridView.PresetThemes.Dark;
            // 
            // btn_nuevo
            // 
            this.btn_nuevo.AllowAnimations = true;
            this.btn_nuevo.AllowMouseEffects = true;
            this.btn_nuevo.AllowToggling = false;
            this.btn_nuevo.AnimationSpeed = 200;
            this.btn_nuevo.AutoGenerateColors = false;
            this.btn_nuevo.AutoRoundBorders = false;
            this.btn_nuevo.AutoSizeLeftIcon = true;
            this.btn_nuevo.AutoSizeRightIcon = true;
            this.btn_nuevo.BackColor = System.Drawing.Color.Transparent;
            this.btn_nuevo.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(51)))), ((int)(((byte)(122)))), ((int)(((byte)(183)))));
            this.btn_nuevo.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btn_nuevo.BackgroundImage")));
            this.btn_nuevo.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btn_nuevo.ButtonText = "NUEVO";
            this.btn_nuevo.ButtonTextMarginLeft = 0;
            this.btn_nuevo.ColorContrastOnClick = 45;
            this.btn_nuevo.ColorContrastOnHover = 45;
            this.btn_nuevo.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges1.BottomLeft = true;
            borderEdges1.BottomRight = true;
            borderEdges1.TopLeft = true;
            borderEdges1.TopRight = true;
            this.btn_nuevo.CustomizableEdges = borderEdges1;
            this.btn_nuevo.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btn_nuevo.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btn_nuevo.DisabledFillColor = System.Drawing.Color.Empty;
            this.btn_nuevo.DisabledForecolor = System.Drawing.Color.Empty;
            this.btn_nuevo.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.btn_nuevo.Font = new System.Drawing.Font("Segoe UI", 14.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.btn_nuevo.ForeColor = System.Drawing.Color.White;
            this.btn_nuevo.IconLeft = null;
            this.btn_nuevo.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btn_nuevo.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btn_nuevo.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.btn_nuevo.IconMarginLeft = 11;
            this.btn_nuevo.IconPadding = 10;
            this.btn_nuevo.IconRight = null;
            this.btn_nuevo.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btn_nuevo.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btn_nuevo.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btn_nuevo.IconSize = 25;
            this.btn_nuevo.IdleBorderColor = System.Drawing.Color.Empty;
            this.btn_nuevo.IdleBorderRadius = 0;
            this.btn_nuevo.IdleBorderThickness = 0;
            this.btn_nuevo.IdleFillColor = System.Drawing.Color.Empty;
            this.btn_nuevo.IdleIconLeftImage = null;
            this.btn_nuevo.IdleIconRightImage = null;
            this.btn_nuevo.IndicateFocus = false;
            this.btn_nuevo.Location = new System.Drawing.Point(12, 523);
            this.btn_nuevo.Name = "btn_nuevo";
            this.btn_nuevo.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btn_nuevo.OnDisabledState.BorderRadius = 1;
            this.btn_nuevo.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btn_nuevo.OnDisabledState.BorderThickness = 1;
            this.btn_nuevo.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btn_nuevo.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btn_nuevo.OnDisabledState.IconLeftImage = null;
            this.btn_nuevo.OnDisabledState.IconRightImage = null;
            this.btn_nuevo.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(30)))), ((int)(((byte)(150)))), ((int)(((byte)(255)))));
            this.btn_nuevo.onHoverState.BorderRadius = 1;
            this.btn_nuevo.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btn_nuevo.onHoverState.BorderThickness = 1;
            this.btn_nuevo.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(30)))), ((int)(((byte)(150)))), ((int)(((byte)(255)))));
            this.btn_nuevo.onHoverState.ForeColor = System.Drawing.Color.White;
            this.btn_nuevo.onHoverState.IconLeftImage = null;
            this.btn_nuevo.onHoverState.IconRightImage = null;
            this.btn_nuevo.OnIdleState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(2)))), ((int)(((byte)(56)))), ((int)(((byte)(119)))));
            this.btn_nuevo.OnIdleState.BorderRadius = 1;
            this.btn_nuevo.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btn_nuevo.OnIdleState.BorderThickness = 1;
            this.btn_nuevo.OnIdleState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(2)))), ((int)(((byte)(56)))), ((int)(((byte)(119)))));
            this.btn_nuevo.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.btn_nuevo.OnIdleState.IconLeftImage = null;
            this.btn_nuevo.OnIdleState.IconRightImage = null;
            this.btn_nuevo.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btn_nuevo.OnPressedState.BorderRadius = 1;
            this.btn_nuevo.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btn_nuevo.OnPressedState.BorderThickness = 1;
            this.btn_nuevo.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btn_nuevo.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.btn_nuevo.OnPressedState.IconLeftImage = null;
            this.btn_nuevo.OnPressedState.IconRightImage = null;
            this.btn_nuevo.Size = new System.Drawing.Size(126, 61);
            this.btn_nuevo.TabIndex = 4;
            this.btn_nuevo.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btn_nuevo.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btn_nuevo.TextMarginLeft = 0;
            this.btn_nuevo.TextPadding = new System.Windows.Forms.Padding(0);
            this.btn_nuevo.UseDefaultRadiusAndThickness = true;
            this.btn_nuevo.Click += new System.EventHandler(this.btn_nuevo_Click);
            // 
            // btn_editar
            // 
            this.btn_editar.AllowAnimations = true;
            this.btn_editar.AllowMouseEffects = true;
            this.btn_editar.AllowToggling = false;
            this.btn_editar.AnimationSpeed = 200;
            this.btn_editar.AutoGenerateColors = false;
            this.btn_editar.AutoRoundBorders = false;
            this.btn_editar.AutoSizeLeftIcon = true;
            this.btn_editar.AutoSizeRightIcon = true;
            this.btn_editar.BackColor = System.Drawing.Color.Transparent;
            this.btn_editar.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(51)))), ((int)(((byte)(122)))), ((int)(((byte)(183)))));
            this.btn_editar.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btn_editar.BackgroundImage")));
            this.btn_editar.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btn_editar.ButtonText = "EDITAR";
            this.btn_editar.ButtonTextMarginLeft = 0;
            this.btn_editar.ColorContrastOnClick = 45;
            this.btn_editar.ColorContrastOnHover = 45;
            this.btn_editar.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges2.BottomLeft = true;
            borderEdges2.BottomRight = true;
            borderEdges2.TopLeft = true;
            borderEdges2.TopRight = true;
            this.btn_editar.CustomizableEdges = borderEdges2;
            this.btn_editar.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btn_editar.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btn_editar.DisabledFillColor = System.Drawing.Color.Empty;
            this.btn_editar.DisabledForecolor = System.Drawing.Color.Empty;
            this.btn_editar.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.btn_editar.Font = new System.Drawing.Font("Segoe UI", 14.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.btn_editar.ForeColor = System.Drawing.Color.White;
            this.btn_editar.IconLeft = null;
            this.btn_editar.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btn_editar.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btn_editar.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.btn_editar.IconMarginLeft = 11;
            this.btn_editar.IconPadding = 10;
            this.btn_editar.IconRight = null;
            this.btn_editar.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btn_editar.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btn_editar.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btn_editar.IconSize = 25;
            this.btn_editar.IdleBorderColor = System.Drawing.Color.Empty;
            this.btn_editar.IdleBorderRadius = 0;
            this.btn_editar.IdleBorderThickness = 0;
            this.btn_editar.IdleFillColor = System.Drawing.Color.Empty;
            this.btn_editar.IdleIconLeftImage = null;
            this.btn_editar.IdleIconRightImage = null;
            this.btn_editar.IndicateFocus = false;
            this.btn_editar.Location = new System.Drawing.Point(355, 523);
            this.btn_editar.Name = "btn_editar";
            this.btn_editar.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btn_editar.OnDisabledState.BorderRadius = 1;
            this.btn_editar.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btn_editar.OnDisabledState.BorderThickness = 1;
            this.btn_editar.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btn_editar.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btn_editar.OnDisabledState.IconLeftImage = null;
            this.btn_editar.OnDisabledState.IconRightImage = null;
            this.btn_editar.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(30)))), ((int)(((byte)(150)))), ((int)(((byte)(255)))));
            this.btn_editar.onHoverState.BorderRadius = 1;
            this.btn_editar.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btn_editar.onHoverState.BorderThickness = 1;
            this.btn_editar.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(30)))), ((int)(((byte)(150)))), ((int)(((byte)(255)))));
            this.btn_editar.onHoverState.ForeColor = System.Drawing.Color.White;
            this.btn_editar.onHoverState.IconLeftImage = null;
            this.btn_editar.onHoverState.IconRightImage = null;
            this.btn_editar.OnIdleState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(2)))), ((int)(((byte)(56)))), ((int)(((byte)(119)))));
            this.btn_editar.OnIdleState.BorderRadius = 1;
            this.btn_editar.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btn_editar.OnIdleState.BorderThickness = 1;
            this.btn_editar.OnIdleState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(2)))), ((int)(((byte)(56)))), ((int)(((byte)(119)))));
            this.btn_editar.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.btn_editar.OnIdleState.IconLeftImage = null;
            this.btn_editar.OnIdleState.IconRightImage = null;
            this.btn_editar.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btn_editar.OnPressedState.BorderRadius = 1;
            this.btn_editar.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btn_editar.OnPressedState.BorderThickness = 1;
            this.btn_editar.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btn_editar.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.btn_editar.OnPressedState.IconLeftImage = null;
            this.btn_editar.OnPressedState.IconRightImage = null;
            this.btn_editar.Size = new System.Drawing.Size(126, 61);
            this.btn_editar.TabIndex = 5;
            this.btn_editar.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btn_editar.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btn_editar.TextMarginLeft = 0;
            this.btn_editar.TextPadding = new System.Windows.Forms.Padding(0);
            this.btn_editar.UseDefaultRadiusAndThickness = true;
            this.btn_editar.Click += new System.EventHandler(this.btn_editar_Click);
            // 
            // btn_eliminar
            // 
            this.btn_eliminar.AllowAnimations = true;
            this.btn_eliminar.AllowMouseEffects = true;
            this.btn_eliminar.AllowToggling = false;
            this.btn_eliminar.AnimationSpeed = 200;
            this.btn_eliminar.AutoGenerateColors = false;
            this.btn_eliminar.AutoRoundBorders = false;
            this.btn_eliminar.AutoSizeLeftIcon = true;
            this.btn_eliminar.AutoSizeRightIcon = true;
            this.btn_eliminar.BackColor = System.Drawing.Color.Transparent;
            this.btn_eliminar.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(51)))), ((int)(((byte)(122)))), ((int)(((byte)(183)))));
            this.btn_eliminar.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btn_eliminar.BackgroundImage")));
            this.btn_eliminar.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btn_eliminar.ButtonText = "ELIMINAR";
            this.btn_eliminar.ButtonTextMarginLeft = 0;
            this.btn_eliminar.ColorContrastOnClick = 45;
            this.btn_eliminar.ColorContrastOnHover = 45;
            this.btn_eliminar.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges3.BottomLeft = true;
            borderEdges3.BottomRight = true;
            borderEdges3.TopLeft = true;
            borderEdges3.TopRight = true;
            this.btn_eliminar.CustomizableEdges = borderEdges3;
            this.btn_eliminar.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btn_eliminar.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btn_eliminar.DisabledFillColor = System.Drawing.Color.Empty;
            this.btn_eliminar.DisabledForecolor = System.Drawing.Color.Empty;
            this.btn_eliminar.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.btn_eliminar.Font = new System.Drawing.Font("Segoe UI", 14.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.btn_eliminar.ForeColor = System.Drawing.Color.White;
            this.btn_eliminar.IconLeft = null;
            this.btn_eliminar.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btn_eliminar.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btn_eliminar.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.btn_eliminar.IconMarginLeft = 11;
            this.btn_eliminar.IconPadding = 10;
            this.btn_eliminar.IconRight = null;
            this.btn_eliminar.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btn_eliminar.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btn_eliminar.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btn_eliminar.IconSize = 25;
            this.btn_eliminar.IdleBorderColor = System.Drawing.Color.Empty;
            this.btn_eliminar.IdleBorderRadius = 0;
            this.btn_eliminar.IdleBorderThickness = 0;
            this.btn_eliminar.IdleFillColor = System.Drawing.Color.Empty;
            this.btn_eliminar.IdleIconLeftImage = null;
            this.btn_eliminar.IdleIconRightImage = null;
            this.btn_eliminar.IndicateFocus = false;
            this.btn_eliminar.Location = new System.Drawing.Point(174, 523);
            this.btn_eliminar.Name = "btn_eliminar";
            this.btn_eliminar.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btn_eliminar.OnDisabledState.BorderRadius = 1;
            this.btn_eliminar.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btn_eliminar.OnDisabledState.BorderThickness = 1;
            this.btn_eliminar.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btn_eliminar.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btn_eliminar.OnDisabledState.IconLeftImage = null;
            this.btn_eliminar.OnDisabledState.IconRightImage = null;
            this.btn_eliminar.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(30)))), ((int)(((byte)(150)))), ((int)(((byte)(255)))));
            this.btn_eliminar.onHoverState.BorderRadius = 1;
            this.btn_eliminar.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btn_eliminar.onHoverState.BorderThickness = 1;
            this.btn_eliminar.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(30)))), ((int)(((byte)(150)))), ((int)(((byte)(255)))));
            this.btn_eliminar.onHoverState.ForeColor = System.Drawing.Color.White;
            this.btn_eliminar.onHoverState.IconLeftImage = null;
            this.btn_eliminar.onHoverState.IconRightImage = null;
            this.btn_eliminar.OnIdleState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(2)))), ((int)(((byte)(56)))), ((int)(((byte)(119)))));
            this.btn_eliminar.OnIdleState.BorderRadius = 1;
            this.btn_eliminar.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btn_eliminar.OnIdleState.BorderThickness = 1;
            this.btn_eliminar.OnIdleState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(2)))), ((int)(((byte)(56)))), ((int)(((byte)(119)))));
            this.btn_eliminar.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.btn_eliminar.OnIdleState.IconLeftImage = null;
            this.btn_eliminar.OnIdleState.IconRightImage = null;
            this.btn_eliminar.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btn_eliminar.OnPressedState.BorderRadius = 1;
            this.btn_eliminar.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btn_eliminar.OnPressedState.BorderThickness = 1;
            this.btn_eliminar.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btn_eliminar.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.btn_eliminar.OnPressedState.IconLeftImage = null;
            this.btn_eliminar.OnPressedState.IconRightImage = null;
            this.btn_eliminar.Size = new System.Drawing.Size(126, 61);
            this.btn_eliminar.TabIndex = 6;
            this.btn_eliminar.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btn_eliminar.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btn_eliminar.TextMarginLeft = 0;
            this.btn_eliminar.TextPadding = new System.Windows.Forms.Padding(0);
            this.btn_eliminar.UseDefaultRadiusAndThickness = true;
            this.btn_eliminar.Click += new System.EventHandler(this.btn_eliminar_Click);
            // 
            // btn_guardar
            // 
            this.btn_guardar.AllowAnimations = true;
            this.btn_guardar.AllowMouseEffects = true;
            this.btn_guardar.AllowToggling = false;
            this.btn_guardar.AnimationSpeed = 200;
            this.btn_guardar.AutoGenerateColors = false;
            this.btn_guardar.AutoRoundBorders = false;
            this.btn_guardar.AutoSizeLeftIcon = true;
            this.btn_guardar.AutoSizeRightIcon = true;
            this.btn_guardar.BackColor = System.Drawing.Color.Transparent;
            this.btn_guardar.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(51)))), ((int)(((byte)(122)))), ((int)(((byte)(183)))));
            this.btn_guardar.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btn_guardar.BackgroundImage")));
            this.btn_guardar.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btn_guardar.ButtonText = "GUARDAR";
            this.btn_guardar.ButtonTextMarginLeft = 0;
            this.btn_guardar.ColorContrastOnClick = 45;
            this.btn_guardar.ColorContrastOnHover = 45;
            this.btn_guardar.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges4.BottomLeft = true;
            borderEdges4.BottomRight = true;
            borderEdges4.TopLeft = true;
            borderEdges4.TopRight = true;
            this.btn_guardar.CustomizableEdges = borderEdges4;
            this.btn_guardar.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btn_guardar.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btn_guardar.DisabledFillColor = System.Drawing.Color.Empty;
            this.btn_guardar.DisabledForecolor = System.Drawing.Color.Empty;
            this.btn_guardar.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.btn_guardar.Font = new System.Drawing.Font("Segoe UI", 14.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.btn_guardar.ForeColor = System.Drawing.Color.White;
            this.btn_guardar.IconLeft = null;
            this.btn_guardar.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btn_guardar.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btn_guardar.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.btn_guardar.IconMarginLeft = 11;
            this.btn_guardar.IconPadding = 10;
            this.btn_guardar.IconRight = null;
            this.btn_guardar.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btn_guardar.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btn_guardar.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btn_guardar.IconSize = 25;
            this.btn_guardar.IdleBorderColor = System.Drawing.Color.Empty;
            this.btn_guardar.IdleBorderRadius = 0;
            this.btn_guardar.IdleBorderThickness = 0;
            this.btn_guardar.IdleFillColor = System.Drawing.Color.Empty;
            this.btn_guardar.IdleIconLeftImage = null;
            this.btn_guardar.IdleIconRightImage = null;
            this.btn_guardar.IndicateFocus = false;
            this.btn_guardar.Location = new System.Drawing.Point(611, 523);
            this.btn_guardar.Name = "btn_guardar";
            this.btn_guardar.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btn_guardar.OnDisabledState.BorderRadius = 1;
            this.btn_guardar.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btn_guardar.OnDisabledState.BorderThickness = 1;
            this.btn_guardar.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btn_guardar.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btn_guardar.OnDisabledState.IconLeftImage = null;
            this.btn_guardar.OnDisabledState.IconRightImage = null;
            this.btn_guardar.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(30)))), ((int)(((byte)(150)))), ((int)(((byte)(255)))));
            this.btn_guardar.onHoverState.BorderRadius = 1;
            this.btn_guardar.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btn_guardar.onHoverState.BorderThickness = 1;
            this.btn_guardar.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(30)))), ((int)(((byte)(150)))), ((int)(((byte)(255)))));
            this.btn_guardar.onHoverState.ForeColor = System.Drawing.Color.White;
            this.btn_guardar.onHoverState.IconLeftImage = null;
            this.btn_guardar.onHoverState.IconRightImage = null;
            this.btn_guardar.OnIdleState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(2)))), ((int)(((byte)(56)))), ((int)(((byte)(119)))));
            this.btn_guardar.OnIdleState.BorderRadius = 1;
            this.btn_guardar.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btn_guardar.OnIdleState.BorderThickness = 1;
            this.btn_guardar.OnIdleState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(2)))), ((int)(((byte)(56)))), ((int)(((byte)(119)))));
            this.btn_guardar.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.btn_guardar.OnIdleState.IconLeftImage = null;
            this.btn_guardar.OnIdleState.IconRightImage = null;
            this.btn_guardar.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btn_guardar.OnPressedState.BorderRadius = 1;
            this.btn_guardar.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btn_guardar.OnPressedState.BorderThickness = 1;
            this.btn_guardar.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btn_guardar.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.btn_guardar.OnPressedState.IconLeftImage = null;
            this.btn_guardar.OnPressedState.IconRightImage = null;
            this.btn_guardar.Size = new System.Drawing.Size(260, 61);
            this.btn_guardar.TabIndex = 7;
            this.btn_guardar.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btn_guardar.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btn_guardar.TextMarginLeft = 0;
            this.btn_guardar.TextPadding = new System.Windows.Forms.Padding(0);
            this.btn_guardar.UseDefaultRadiusAndThickness = true;
            this.btn_guardar.Click += new System.EventHandler(this.btn_guardar_Click);
            // 
            // buscarcod
            // 
            this.buscarcod.AcceptsReturn = false;
            this.buscarcod.AcceptsTab = false;
            this.buscarcod.AnimationSpeed = 200;
            this.buscarcod.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.buscarcod.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.buscarcod.AutoSizeHeight = true;
            this.buscarcod.BackColor = System.Drawing.Color.White;
            this.buscarcod.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("buscarcod.BackgroundImage")));
            this.buscarcod.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.buscarcod.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.buscarcod.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.buscarcod.BorderColorIdle = System.Drawing.Color.Silver;
            this.buscarcod.BorderRadius = 1;
            this.buscarcod.BorderThickness = 1;
            this.buscarcod.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.buscarcod.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.buscarcod.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.buscarcod.DefaultText = "";
            this.buscarcod.FillColor = System.Drawing.Color.White;
            this.buscarcod.HideSelection = true;
            this.buscarcod.IconLeft = null;
            this.buscarcod.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.buscarcod.IconPadding = 10;
            this.buscarcod.IconRight = null;
            this.buscarcod.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.buscarcod.Lines = new string[0];
            this.buscarcod.Location = new System.Drawing.Point(611, 259);
            this.buscarcod.MaxLength = 32767;
            this.buscarcod.MinimumSize = new System.Drawing.Size(1, 1);
            this.buscarcod.Modified = false;
            this.buscarcod.Multiline = false;
            this.buscarcod.Name = "buscarcod";
            stateProperties5.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties5.FillColor = System.Drawing.Color.Empty;
            stateProperties5.ForeColor = System.Drawing.Color.Empty;
            stateProperties5.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.buscarcod.OnActiveState = stateProperties5;
            stateProperties6.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties6.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties6.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties6.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.buscarcod.OnDisabledState = stateProperties6;
            stateProperties7.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties7.FillColor = System.Drawing.Color.Empty;
            stateProperties7.ForeColor = System.Drawing.Color.Empty;
            stateProperties7.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.buscarcod.OnHoverState = stateProperties7;
            stateProperties8.BorderColor = System.Drawing.Color.Silver;
            stateProperties8.FillColor = System.Drawing.Color.White;
            stateProperties8.ForeColor = System.Drawing.Color.Empty;
            stateProperties8.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.buscarcod.OnIdleState = stateProperties8;
            this.buscarcod.Padding = new System.Windows.Forms.Padding(3);
            this.buscarcod.PasswordChar = '\0';
            this.buscarcod.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.buscarcod.PlaceholderText = "Enter text";
            this.buscarcod.ReadOnly = false;
            this.buscarcod.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.buscarcod.SelectedText = "";
            this.buscarcod.SelectionLength = 0;
            this.buscarcod.SelectionStart = 0;
            this.buscarcod.ShortcutsEnabled = true;
            this.buscarcod.Size = new System.Drawing.Size(260, 39);
            this.buscarcod.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Material;
            this.buscarcod.TabIndex = 8;
            this.buscarcod.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.buscarcod.TextMarginBottom = 0;
            this.buscarcod.TextMarginLeft = 3;
            this.buscarcod.TextMarginTop = 1;
            this.buscarcod.TextPlaceholder = "Enter text";
            this.buscarcod.UseSystemPasswordChar = false;
            this.buscarcod.WordWrap = true;
            // 
            // buscaraula
            // 
            this.buscaraula.AcceptsReturn = false;
            this.buscaraula.AcceptsTab = false;
            this.buscaraula.AnimationSpeed = 200;
            this.buscaraula.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.buscaraula.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.buscaraula.AutoSizeHeight = true;
            this.buscaraula.BackColor = System.Drawing.Color.White;
            this.buscaraula.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("buscaraula.BackgroundImage")));
            this.buscaraula.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.buscaraula.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.buscaraula.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.buscaraula.BorderColorIdle = System.Drawing.Color.Silver;
            this.buscaraula.BorderRadius = 1;
            this.buscaraula.BorderThickness = 1;
            this.buscaraula.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.buscaraula.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.buscaraula.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.buscaraula.DefaultText = "";
            this.buscaraula.FillColor = System.Drawing.Color.White;
            this.buscaraula.HideSelection = true;
            this.buscaraula.IconLeft = null;
            this.buscaraula.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.buscaraula.IconPadding = 10;
            this.buscaraula.IconRight = null;
            this.buscaraula.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.buscaraula.Lines = new string[0];
            this.buscaraula.Location = new System.Drawing.Point(611, 345);
            this.buscaraula.MaxLength = 32767;
            this.buscaraula.MinimumSize = new System.Drawing.Size(1, 1);
            this.buscaraula.Modified = false;
            this.buscaraula.Multiline = false;
            this.buscaraula.Name = "buscaraula";
            stateProperties9.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties9.FillColor = System.Drawing.Color.Empty;
            stateProperties9.ForeColor = System.Drawing.Color.Empty;
            stateProperties9.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.buscaraula.OnActiveState = stateProperties9;
            stateProperties10.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties10.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties10.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties10.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.buscaraula.OnDisabledState = stateProperties10;
            stateProperties11.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties11.FillColor = System.Drawing.Color.Empty;
            stateProperties11.ForeColor = System.Drawing.Color.Empty;
            stateProperties11.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.buscaraula.OnHoverState = stateProperties11;
            stateProperties12.BorderColor = System.Drawing.Color.Silver;
            stateProperties12.FillColor = System.Drawing.Color.White;
            stateProperties12.ForeColor = System.Drawing.Color.Empty;
            stateProperties12.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.buscaraula.OnIdleState = stateProperties12;
            this.buscaraula.Padding = new System.Windows.Forms.Padding(3);
            this.buscaraula.PasswordChar = '\0';
            this.buscaraula.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.buscaraula.PlaceholderText = "Enter text";
            this.buscaraula.ReadOnly = false;
            this.buscaraula.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.buscaraula.SelectedText = "";
            this.buscaraula.SelectionLength = 0;
            this.buscaraula.SelectionStart = 0;
            this.buscaraula.ShortcutsEnabled = true;
            this.buscaraula.Size = new System.Drawing.Size(260, 39);
            this.buscaraula.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Material;
            this.buscaraula.TabIndex = 9;
            this.buscaraula.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.buscaraula.TextMarginBottom = 0;
            this.buscaraula.TextMarginLeft = 3;
            this.buscaraula.TextMarginTop = 1;
            this.buscaraula.TextPlaceholder = "Enter text";
            this.buscaraula.UseSystemPasswordChar = false;
            this.buscaraula.WordWrap = true;
            // 
            // buscaredificio
            // 
            this.buscaredificio.AcceptsReturn = false;
            this.buscaredificio.AcceptsTab = false;
            this.buscaredificio.AnimationSpeed = 200;
            this.buscaredificio.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.buscaredificio.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.buscaredificio.AutoSizeHeight = true;
            this.buscaredificio.BackColor = System.Drawing.Color.White;
            this.buscaredificio.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("buscaredificio.BackgroundImage")));
            this.buscaredificio.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.buscaredificio.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.buscaredificio.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.buscaredificio.BorderColorIdle = System.Drawing.Color.Silver;
            this.buscaredificio.BorderRadius = 1;
            this.buscaredificio.BorderThickness = 1;
            this.buscaredificio.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.buscaredificio.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.buscaredificio.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.buscaredificio.DefaultText = "";
            this.buscaredificio.FillColor = System.Drawing.Color.White;
            this.buscaredificio.HideSelection = true;
            this.buscaredificio.IconLeft = null;
            this.buscaredificio.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.buscaredificio.IconPadding = 10;
            this.buscaredificio.IconRight = null;
            this.buscaredificio.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.buscaredificio.Lines = new string[0];
            this.buscaredificio.Location = new System.Drawing.Point(611, 441);
            this.buscaredificio.MaxLength = 32767;
            this.buscaredificio.MinimumSize = new System.Drawing.Size(1, 1);
            this.buscaredificio.Modified = false;
            this.buscaredificio.Multiline = false;
            this.buscaredificio.Name = "buscaredificio";
            stateProperties13.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties13.FillColor = System.Drawing.Color.Empty;
            stateProperties13.ForeColor = System.Drawing.Color.Empty;
            stateProperties13.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.buscaredificio.OnActiveState = stateProperties13;
            stateProperties14.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties14.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties14.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties14.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.buscaredificio.OnDisabledState = stateProperties14;
            stateProperties15.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties15.FillColor = System.Drawing.Color.Empty;
            stateProperties15.ForeColor = System.Drawing.Color.Empty;
            stateProperties15.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.buscaredificio.OnHoverState = stateProperties15;
            stateProperties16.BorderColor = System.Drawing.Color.Silver;
            stateProperties16.FillColor = System.Drawing.Color.White;
            stateProperties16.ForeColor = System.Drawing.Color.Empty;
            stateProperties16.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.buscaredificio.OnIdleState = stateProperties16;
            this.buscaredificio.Padding = new System.Windows.Forms.Padding(3);
            this.buscaredificio.PasswordChar = '\0';
            this.buscaredificio.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.buscaredificio.PlaceholderText = "Enter text";
            this.buscaredificio.ReadOnly = false;
            this.buscaredificio.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.buscaredificio.SelectedText = "";
            this.buscaredificio.SelectionLength = 0;
            this.buscaredificio.SelectionStart = 0;
            this.buscaredificio.ShortcutsEnabled = true;
            this.buscaredificio.Size = new System.Drawing.Size(260, 39);
            this.buscaredificio.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Material;
            this.buscaredificio.TabIndex = 10;
            this.buscaredificio.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.buscaredificio.TextMarginBottom = 0;
            this.buscaredificio.TextMarginLeft = 3;
            this.buscaredificio.TextMarginTop = 1;
            this.buscaredificio.TextPlaceholder = "Enter text";
            this.buscaredificio.UseSystemPasswordChar = false;
            this.buscaredificio.WordWrap = true;
            // 
            // bunifuLabel2
            // 
            this.bunifuLabel2.AllowParentOverrides = false;
            this.bunifuLabel2.AutoEllipsis = false;
            this.bunifuLabel2.CursorType = System.Windows.Forms.Cursors.Default;
            this.bunifuLabel2.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.bunifuLabel2.Location = new System.Drawing.Point(611, 238);
            this.bunifuLabel2.Name = "bunifuLabel2";
            this.bunifuLabel2.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.bunifuLabel2.Size = new System.Drawing.Size(25, 15);
            this.bunifuLabel2.TabIndex = 11;
            this.bunifuLabel2.Text = "COD";
            this.bunifuLabel2.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.bunifuLabel2.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // bunifuLabel3
            // 
            this.bunifuLabel3.AllowParentOverrides = false;
            this.bunifuLabel3.AutoEllipsis = false;
            this.bunifuLabel3.CursorType = null;
            this.bunifuLabel3.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.bunifuLabel3.Location = new System.Drawing.Point(611, 324);
            this.bunifuLabel3.Name = "bunifuLabel3";
            this.bunifuLabel3.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.bunifuLabel3.Size = new System.Drawing.Size(30, 15);
            this.bunifuLabel3.TabIndex = 12;
            this.bunifuLabel3.Text = "AULA";
            this.bunifuLabel3.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.bunifuLabel3.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // bunifuLabel4
            // 
            this.bunifuLabel4.AllowParentOverrides = false;
            this.bunifuLabel4.AutoEllipsis = false;
            this.bunifuLabel4.CursorType = null;
            this.bunifuLabel4.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.bunifuLabel4.Location = new System.Drawing.Point(611, 420);
            this.bunifuLabel4.Name = "bunifuLabel4";
            this.bunifuLabel4.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.bunifuLabel4.Size = new System.Drawing.Size(46, 15);
            this.bunifuLabel4.TabIndex = 13;
            this.bunifuLabel4.Text = "EDIFICIO";
            this.bunifuLabel4.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.bunifuLabel4.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // AULAS_FORM
            // 
            this.AutoScaleDimensions = new System.Drawing.SizeF(6F, 13F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.ClientSize = new System.Drawing.Size(922, 596);
            this.Controls.Add(this.bunifuLabel4);
            this.Controls.Add(this.bunifuLabel3);
            this.Controls.Add(this.bunifuLabel2);
            this.Controls.Add(this.buscaredificio);
            this.Controls.Add(this.buscaraula);
            this.Controls.Add(this.buscarcod);
            this.Controls.Add(this.btn_guardar);
            this.Controls.Add(this.btn_eliminar);
            this.Controls.Add(this.btn_editar);
            this.Controls.Add(this.btn_nuevo);
            this.Controls.Add(this.tabla);
            this.Controls.Add(this.bunifuPictureBox2);
            this.Controls.Add(this.buscar);
            this.Controls.Add(this.bunifuPanel1);
            this.FormBorderStyle = System.Windows.Forms.FormBorderStyle.None;
            this.Name = "AULAS_FORM";
            this.StartPosition = System.Windows.Forms.FormStartPosition.CenterScreen;
            this.Text = "Form1";
            this.Load += new System.EventHandler(this.AULAS_FORM_Load);
            this.bunifuPanel1.ResumeLayout(false);
            this.bunifuPanel1.PerformLayout();
            ((System.ComponentModel.ISupportInitialize)(this.bunifuPictureBox1)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.bunifuPictureBox2)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.tabla)).EndInit();
            this.ResumeLayout(false);
            this.PerformLayout();

        }

        #endregion

        private Bunifu.UI.WinForms.BunifuPanel bunifuPanel1;
        private Bunifu.UI.WinForms.BunifuPictureBox bunifuPictureBox1;
        private Bunifu.UI.WinForms.BunifuLabel bunifuLabel1;
        private Bunifu.UI.WinForms.BunifuTextBox buscar;
        private Bunifu.UI.WinForms.BunifuPictureBox bunifuPictureBox2;
        private Bunifu.UI.WinForms.BunifuDataGridView tabla;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton btn_nuevo;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton btn_editar;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton btn_eliminar;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton btn_guardar;
        private Bunifu.UI.WinForms.BunifuTextBox buscarcod;
        private Bunifu.UI.WinForms.BunifuTextBox buscaraula;
        private Bunifu.UI.WinForms.BunifuTextBox buscaredificio;
        private Bunifu.UI.WinForms.BunifuLabel bunifuLabel2;
        private Bunifu.UI.WinForms.BunifuLabel bunifuLabel3;
        private Bunifu.UI.WinForms.BunifuLabel bunifuLabel4;
    }
}