
namespace Final_project
{
    partial class MOD_VISITAS
    {
        /// <summary>
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary>
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

        /// <summary>
        /// Required method for Designer support - do not modify
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(MOD_VISITAS));
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties1 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties2 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties3 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties4 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties5 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties6 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties7 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties8 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties9 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties10 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties11 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties12 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties13 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties14 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties15 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties16 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties17 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties18 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties19 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties20 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            System.Windows.Forms.DataGridViewCellStyle dataGridViewCellStyle1 = new System.Windows.Forms.DataGridViewCellStyle();
            System.Windows.Forms.DataGridViewCellStyle dataGridViewCellStyle2 = new System.Windows.Forms.DataGridViewCellStyle();
            System.Windows.Forms.DataGridViewCellStyle dataGridViewCellStyle3 = new System.Windows.Forms.DataGridViewCellStyle();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties21 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties22 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties23 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties24 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges1 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges2 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties25 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties26 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties27 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties28 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            this.c_aula = new Bunifu.UI.WinForms.BunifuDropdown();
            this.c_edificio = new Bunifu.UI.WinForms.BunifuDropdown();
            this.Mod_visitor = new Bunifu.Framework.UI.BunifuThinButton2();
            this.carrera_TextBox1 = new Bunifu.UI.WinForms.BunifuTextBox();
            this.mot_TextBox1 = new Bunifu.UI.WinForms.BunifuTextBox();
            this.Sal_DatePicker1 = new Bunifu.UI.WinForms.BunifuDatePicker();
            this.Ent_DatePicker1 = new Bunifu.UI.WinForms.BunifuDatePicker();
            this.c_correo = new Bunifu.UI.WinForms.BunifuTextBox();
            this.c_apellido = new Bunifu.UI.WinForms.BunifuTextBox();
            this.C_nombre = new Bunifu.UI.WinForms.BunifuTextBox();
            this.bunifuLabel1 = new Bunifu.UI.WinForms.BunifuLabel();
            this.tabla = new Bunifu.UI.WinForms.BunifuDataGridView();
            this.bunifuLabel2 = new Bunifu.UI.WinForms.BunifuLabel();
            this.search = new Bunifu.UI.WinForms.BunifuTextBox();
            this.button_search = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.Safe = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.codigo = new Bunifu.UI.WinForms.BunifuTextBox();
            ((System.ComponentModel.ISupportInitialize)(this.tabla)).BeginInit();
            this.SuspendLayout();
            // 
            // c_aula
            // 
            this.c_aula.BackColor = System.Drawing.Color.Transparent;
            this.c_aula.BackgroundColor = System.Drawing.Color.White;
            this.c_aula.BorderColor = System.Drawing.Color.Silver;
            this.c_aula.BorderRadius = 1;
            this.c_aula.Color = System.Drawing.Color.Silver;
            this.c_aula.Direction = Bunifu.UI.WinForms.BunifuDropdown.Directions.Down;
            this.c_aula.DisabledBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            this.c_aula.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.c_aula.DisabledColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            this.c_aula.DisabledForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            this.c_aula.DisabledIndicatorColor = System.Drawing.Color.DarkGray;
            this.c_aula.DrawMode = System.Windows.Forms.DrawMode.OwnerDrawFixed;
            this.c_aula.DropdownBorderThickness = Bunifu.UI.WinForms.BunifuDropdown.BorderThickness.Thin;
            this.c_aula.DropDownStyle = System.Windows.Forms.ComboBoxStyle.DropDownList;
            this.c_aula.DropDownTextAlign = Bunifu.UI.WinForms.BunifuDropdown.TextAlign.Left;
            this.c_aula.FillDropDown = true;
            this.c_aula.FillIndicator = false;
            this.c_aula.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
            this.c_aula.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.c_aula.ForeColor = System.Drawing.Color.Black;
            this.c_aula.FormattingEnabled = true;
            this.c_aula.Icon = null;
            this.c_aula.IndicatorAlignment = Bunifu.UI.WinForms.BunifuDropdown.Indicator.Right;
            this.c_aula.IndicatorColor = System.Drawing.Color.DarkGray;
            this.c_aula.IndicatorLocation = Bunifu.UI.WinForms.BunifuDropdown.Indicator.Right;
            this.c_aula.IndicatorThickness = 2;
            this.c_aula.IsDropdownOpened = false;
            this.c_aula.ItemBackColor = System.Drawing.Color.White;
            this.c_aula.ItemBorderColor = System.Drawing.Color.White;
            this.c_aula.ItemForeColor = System.Drawing.Color.Black;
            this.c_aula.ItemHeight = 26;
            this.c_aula.ItemHighLightColor = System.Drawing.Color.DodgerBlue;
            this.c_aula.ItemHighLightForeColor = System.Drawing.Color.White;
            this.c_aula.ItemTopMargin = 3;
            this.c_aula.Location = new System.Drawing.Point(603, 308);
            this.c_aula.Name = "c_aula";
            this.c_aula.Size = new System.Drawing.Size(305, 32);
            this.c_aula.TabIndex = 21;
            this.c_aula.Text = "Aula";
            this.c_aula.TextAlignment = Bunifu.UI.WinForms.BunifuDropdown.TextAlign.Left;
            this.c_aula.TextLeftMargin = 5;
            // 
            // c_edificio
            // 
            this.c_edificio.BackColor = System.Drawing.Color.Transparent;
            this.c_edificio.BackgroundColor = System.Drawing.Color.White;
            this.c_edificio.BorderColor = System.Drawing.Color.Silver;
            this.c_edificio.BorderRadius = 1;
            this.c_edificio.Color = System.Drawing.Color.Silver;
            this.c_edificio.Direction = Bunifu.UI.WinForms.BunifuDropdown.Directions.Down;
            this.c_edificio.DisabledBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            this.c_edificio.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.c_edificio.DisabledColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            this.c_edificio.DisabledForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            this.c_edificio.DisabledIndicatorColor = System.Drawing.Color.DarkGray;
            this.c_edificio.DrawMode = System.Windows.Forms.DrawMode.OwnerDrawFixed;
            this.c_edificio.DropdownBorderThickness = Bunifu.UI.WinForms.BunifuDropdown.BorderThickness.Thin;
            this.c_edificio.DropDownStyle = System.Windows.Forms.ComboBoxStyle.DropDownList;
            this.c_edificio.DropDownTextAlign = Bunifu.UI.WinForms.BunifuDropdown.TextAlign.Left;
            this.c_edificio.FillDropDown = true;
            this.c_edificio.FillIndicator = false;
            this.c_edificio.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
            this.c_edificio.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.c_edificio.ForeColor = System.Drawing.Color.Black;
            this.c_edificio.FormattingEnabled = true;
            this.c_edificio.Icon = null;
            this.c_edificio.IndicatorAlignment = Bunifu.UI.WinForms.BunifuDropdown.Indicator.Right;
            this.c_edificio.IndicatorColor = System.Drawing.Color.DarkGray;
            this.c_edificio.IndicatorLocation = Bunifu.UI.WinForms.BunifuDropdown.Indicator.Right;
            this.c_edificio.IndicatorThickness = 2;
            this.c_edificio.IsDropdownOpened = false;
            this.c_edificio.ItemBackColor = System.Drawing.Color.White;
            this.c_edificio.ItemBorderColor = System.Drawing.Color.White;
            this.c_edificio.ItemForeColor = System.Drawing.Color.Black;
            this.c_edificio.ItemHeight = 26;
            this.c_edificio.ItemHighLightColor = System.Drawing.Color.DodgerBlue;
            this.c_edificio.ItemHighLightForeColor = System.Drawing.Color.White;
            this.c_edificio.ItemTopMargin = 3;
            this.c_edificio.Location = new System.Drawing.Point(603, 270);
            this.c_edificio.Name = "c_edificio";
            this.c_edificio.Size = new System.Drawing.Size(305, 32);
            this.c_edificio.TabIndex = 16;
            this.c_edificio.Text = "Edificio";
            this.c_edificio.TextAlignment = Bunifu.UI.WinForms.BunifuDropdown.TextAlign.Left;
            this.c_edificio.TextLeftMargin = 5;
            // 
            // Mod_visitor
            // 
            this.Mod_visitor.ActiveBorderThickness = 1;
            this.Mod_visitor.ActiveCornerRadius = 20;
            this.Mod_visitor.ActiveFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(2)))), ((int)(((byte)(56)))), ((int)(((byte)(119)))));
            this.Mod_visitor.ActiveForecolor = System.Drawing.Color.White;
            this.Mod_visitor.ActiveLineColor = System.Drawing.Color.FromArgb(((int)(((byte)(2)))), ((int)(((byte)(56)))), ((int)(((byte)(119)))));
            this.Mod_visitor.BackColor = System.Drawing.SystemColors.Control;
            this.Mod_visitor.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("Mod_visitor.BackgroundImage")));
            this.Mod_visitor.ButtonText = "Modify visitor";
            this.Mod_visitor.Cursor = System.Windows.Forms.Cursors.Hand;
            this.Mod_visitor.Font = new System.Drawing.Font("Century Gothic", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.Mod_visitor.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(2)))), ((int)(((byte)(56)))), ((int)(((byte)(119)))));
            this.Mod_visitor.IdleBorderThickness = 1;
            this.Mod_visitor.IdleCornerRadius = 20;
            this.Mod_visitor.IdleFillColor = System.Drawing.Color.White;
            this.Mod_visitor.IdleForecolor = System.Drawing.Color.SeaGreen;
            this.Mod_visitor.IdleLineColor = System.Drawing.Color.SeaGreen;
            this.Mod_visitor.Location = new System.Drawing.Point(603, 458);
            this.Mod_visitor.Margin = new System.Windows.Forms.Padding(5, 5, 5, 5);
            this.Mod_visitor.Name = "Mod_visitor";
            this.Mod_visitor.Size = new System.Drawing.Size(305, 77);
            this.Mod_visitor.TabIndex = 22;
            this.Mod_visitor.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.Mod_visitor.Click += new System.EventHandler(this.Mod_visitor_Click);
            // 
            // carrera_TextBox1
            // 
            this.carrera_TextBox1.AcceptsReturn = false;
            this.carrera_TextBox1.AcceptsTab = false;
            this.carrera_TextBox1.AnimationSpeed = 200;
            this.carrera_TextBox1.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.carrera_TextBox1.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.carrera_TextBox1.AutoSizeHeight = true;
            this.carrera_TextBox1.BackColor = System.Drawing.Color.White;
            this.carrera_TextBox1.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("carrera_TextBox1.BackgroundImage")));
            this.carrera_TextBox1.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.carrera_TextBox1.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.carrera_TextBox1.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.carrera_TextBox1.BorderColorIdle = System.Drawing.Color.Silver;
            this.carrera_TextBox1.BorderRadius = 10;
            this.carrera_TextBox1.BorderThickness = 2;
            this.carrera_TextBox1.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.carrera_TextBox1.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.carrera_TextBox1.DefaultFont = new System.Drawing.Font("Segoe UI", 9.75F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.carrera_TextBox1.DefaultText = "";
            this.carrera_TextBox1.FillColor = System.Drawing.Color.White;
            this.carrera_TextBox1.HideSelection = true;
            this.carrera_TextBox1.IconLeft = null;
            this.carrera_TextBox1.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.carrera_TextBox1.IconPadding = 10;
            this.carrera_TextBox1.IconRight = null;
            this.carrera_TextBox1.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.carrera_TextBox1.Lines = new string[0];
            this.carrera_TextBox1.Location = new System.Drawing.Point(603, 228);
            this.carrera_TextBox1.MaxLength = 32767;
            this.carrera_TextBox1.MinimumSize = new System.Drawing.Size(1, 1);
            this.carrera_TextBox1.Modified = false;
            this.carrera_TextBox1.Multiline = false;
            this.carrera_TextBox1.Name = "carrera_TextBox1";
            stateProperties1.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties1.FillColor = System.Drawing.Color.Empty;
            stateProperties1.ForeColor = System.Drawing.Color.Empty;
            stateProperties1.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.carrera_TextBox1.OnActiveState = stateProperties1;
            stateProperties2.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties2.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties2.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties2.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.carrera_TextBox1.OnDisabledState = stateProperties2;
            stateProperties3.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties3.FillColor = System.Drawing.Color.Empty;
            stateProperties3.ForeColor = System.Drawing.Color.Empty;
            stateProperties3.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.carrera_TextBox1.OnHoverState = stateProperties3;
            stateProperties4.BorderColor = System.Drawing.Color.Silver;
            stateProperties4.FillColor = System.Drawing.Color.White;
            stateProperties4.ForeColor = System.Drawing.Color.Empty;
            stateProperties4.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.carrera_TextBox1.OnIdleState = stateProperties4;
            this.carrera_TextBox1.Padding = new System.Windows.Forms.Padding(3, 3, 3, 3);
            this.carrera_TextBox1.PasswordChar = '\0';
            this.carrera_TextBox1.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.carrera_TextBox1.PlaceholderText = "Carrera";
            this.carrera_TextBox1.ReadOnly = false;
            this.carrera_TextBox1.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.carrera_TextBox1.SelectedText = "";
            this.carrera_TextBox1.SelectionLength = 0;
            this.carrera_TextBox1.SelectionStart = 0;
            this.carrera_TextBox1.ShortcutsEnabled = true;
            this.carrera_TextBox1.Size = new System.Drawing.Size(305, 36);
            this.carrera_TextBox1.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.carrera_TextBox1.TabIndex = 20;
            this.carrera_TextBox1.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.carrera_TextBox1.TextMarginBottom = 0;
            this.carrera_TextBox1.TextMarginLeft = 3;
            this.carrera_TextBox1.TextMarginTop = 1;
            this.carrera_TextBox1.TextPlaceholder = "Carrera";
            this.carrera_TextBox1.UseSystemPasswordChar = false;
            this.carrera_TextBox1.WordWrap = true;
            // 
            // mot_TextBox1
            // 
            this.mot_TextBox1.AcceptsReturn = false;
            this.mot_TextBox1.AcceptsTab = false;
            this.mot_TextBox1.AnimationSpeed = 200;
            this.mot_TextBox1.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.mot_TextBox1.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.mot_TextBox1.AutoSizeHeight = true;
            this.mot_TextBox1.BackColor = System.Drawing.Color.White;
            this.mot_TextBox1.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("mot_TextBox1.BackgroundImage")));
            this.mot_TextBox1.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.mot_TextBox1.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.mot_TextBox1.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.mot_TextBox1.BorderColorIdle = System.Drawing.Color.Silver;
            this.mot_TextBox1.BorderRadius = 10;
            this.mot_TextBox1.BorderThickness = 2;
            this.mot_TextBox1.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.mot_TextBox1.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.mot_TextBox1.DefaultFont = new System.Drawing.Font("Segoe UI", 9.75F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.mot_TextBox1.DefaultText = "";
            this.mot_TextBox1.FillColor = System.Drawing.Color.White;
            this.mot_TextBox1.HideSelection = true;
            this.mot_TextBox1.IconLeft = null;
            this.mot_TextBox1.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.mot_TextBox1.IconPadding = 10;
            this.mot_TextBox1.IconRight = null;
            this.mot_TextBox1.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.mot_TextBox1.Lines = new string[0];
            this.mot_TextBox1.Location = new System.Drawing.Point(603, 422);
            this.mot_TextBox1.MaxLength = 32767;
            this.mot_TextBox1.MinimumSize = new System.Drawing.Size(1, 1);
            this.mot_TextBox1.Modified = false;
            this.mot_TextBox1.Multiline = true;
            this.mot_TextBox1.Name = "mot_TextBox1";
            stateProperties5.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties5.FillColor = System.Drawing.Color.Empty;
            stateProperties5.ForeColor = System.Drawing.Color.Empty;
            stateProperties5.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.mot_TextBox1.OnActiveState = stateProperties5;
            stateProperties6.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties6.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties6.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties6.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.mot_TextBox1.OnDisabledState = stateProperties6;
            stateProperties7.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties7.FillColor = System.Drawing.Color.Empty;
            stateProperties7.ForeColor = System.Drawing.Color.Empty;
            stateProperties7.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.mot_TextBox1.OnHoverState = stateProperties7;
            stateProperties8.BorderColor = System.Drawing.Color.Silver;
            stateProperties8.FillColor = System.Drawing.Color.White;
            stateProperties8.ForeColor = System.Drawing.Color.Empty;
            stateProperties8.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.mot_TextBox1.OnIdleState = stateProperties8;
            this.mot_TextBox1.Padding = new System.Windows.Forms.Padding(3, 3, 3, 3);
            this.mot_TextBox1.PasswordChar = '\0';
            this.mot_TextBox1.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.mot_TextBox1.PlaceholderText = "Motivo";
            this.mot_TextBox1.ReadOnly = false;
            this.mot_TextBox1.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.mot_TextBox1.SelectedText = "";
            this.mot_TextBox1.SelectionLength = 0;
            this.mot_TextBox1.SelectionStart = 0;
            this.mot_TextBox1.ShortcutsEnabled = true;
            this.mot_TextBox1.Size = new System.Drawing.Size(305, 36);
            this.mot_TextBox1.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.mot_TextBox1.TabIndex = 19;
            this.mot_TextBox1.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.mot_TextBox1.TextMarginBottom = 0;
            this.mot_TextBox1.TextMarginLeft = 3;
            this.mot_TextBox1.TextMarginTop = 1;
            this.mot_TextBox1.TextPlaceholder = "Motivo";
            this.mot_TextBox1.UseSystemPasswordChar = false;
            this.mot_TextBox1.WordWrap = true;
            // 
            // Sal_DatePicker1
            // 
            this.Sal_DatePicker1.BackColor = System.Drawing.Color.Transparent;
            this.Sal_DatePicker1.BorderColor = System.Drawing.Color.Silver;
            this.Sal_DatePicker1.BorderRadius = 10;
            this.Sal_DatePicker1.Color = System.Drawing.Color.Silver;
            this.Sal_DatePicker1.DateBorderThickness = Bunifu.UI.WinForms.BunifuDatePicker.BorderThickness.Thin;
            this.Sal_DatePicker1.DateTextAlign = Bunifu.UI.WinForms.BunifuDatePicker.TextAlign.Left;
            this.Sal_DatePicker1.DisabledColor = System.Drawing.Color.Gray;
            this.Sal_DatePicker1.DisplayWeekNumbers = false;
            this.Sal_DatePicker1.DPHeight = 0;
            this.Sal_DatePicker1.DropDownAlign = System.Windows.Forms.LeftRightAlignment.Right;
            this.Sal_DatePicker1.FillDatePicker = false;
            this.Sal_DatePicker1.Font = new System.Drawing.Font("Lucida Fax", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.Sal_DatePicker1.ForeColor = System.Drawing.Color.Black;
            this.Sal_DatePicker1.Format = System.Windows.Forms.DateTimePickerFormat.Time;
            this.Sal_DatePicker1.Icon = ((System.Drawing.Image)(resources.GetObject("Sal_DatePicker1.Icon")));
            this.Sal_DatePicker1.IconColor = System.Drawing.Color.Gray;
            this.Sal_DatePicker1.IconLocation = Bunifu.UI.WinForms.BunifuDatePicker.Indicator.Right;
            this.Sal_DatePicker1.LeftTextMargin = 5;
            this.Sal_DatePicker1.Location = new System.Drawing.Point(603, 384);
            this.Sal_DatePicker1.MinimumSize = new System.Drawing.Size(4, 32);
            this.Sal_DatePicker1.Name = "Sal_DatePicker1";
            this.Sal_DatePicker1.Size = new System.Drawing.Size(305, 32);
            this.Sal_DatePicker1.TabIndex = 18;
            this.Sal_DatePicker1.Value = new System.DateTime(2022, 12, 17, 19, 47, 0, 0);
            // 
            // Ent_DatePicker1
            // 
            this.Ent_DatePicker1.BackColor = System.Drawing.Color.Transparent;
            this.Ent_DatePicker1.BorderColor = System.Drawing.Color.Silver;
            this.Ent_DatePicker1.BorderRadius = 10;
            this.Ent_DatePicker1.Color = System.Drawing.Color.Silver;
            this.Ent_DatePicker1.DateBorderThickness = Bunifu.UI.WinForms.BunifuDatePicker.BorderThickness.Thin;
            this.Ent_DatePicker1.DateTextAlign = Bunifu.UI.WinForms.BunifuDatePicker.TextAlign.Left;
            this.Ent_DatePicker1.DisabledColor = System.Drawing.Color.Gray;
            this.Ent_DatePicker1.DisplayWeekNumbers = false;
            this.Ent_DatePicker1.DPHeight = 0;
            this.Ent_DatePicker1.DropDownAlign = System.Windows.Forms.LeftRightAlignment.Right;
            this.Ent_DatePicker1.FillDatePicker = false;
            this.Ent_DatePicker1.Font = new System.Drawing.Font("Lucida Fax", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.Ent_DatePicker1.ForeColor = System.Drawing.Color.Black;
            this.Ent_DatePicker1.Format = System.Windows.Forms.DateTimePickerFormat.Time;
            this.Ent_DatePicker1.Icon = ((System.Drawing.Image)(resources.GetObject("Ent_DatePicker1.Icon")));
            this.Ent_DatePicker1.IconColor = System.Drawing.Color.Gray;
            this.Ent_DatePicker1.IconLocation = Bunifu.UI.WinForms.BunifuDatePicker.Indicator.Right;
            this.Ent_DatePicker1.LeftTextMargin = 5;
            this.Ent_DatePicker1.Location = new System.Drawing.Point(603, 346);
            this.Ent_DatePicker1.MinimumSize = new System.Drawing.Size(4, 32);
            this.Ent_DatePicker1.Name = "Ent_DatePicker1";
            this.Ent_DatePicker1.Size = new System.Drawing.Size(305, 32);
            this.Ent_DatePicker1.TabIndex = 17;
            this.Ent_DatePicker1.Value = new System.DateTime(2022, 12, 17, 19, 45, 0, 0);
            // 
            // c_correo
            // 
            this.c_correo.AcceptsReturn = false;
            this.c_correo.AcceptsTab = false;
            this.c_correo.AnimationSpeed = 200;
            this.c_correo.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.c_correo.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.c_correo.AutoSizeHeight = true;
            this.c_correo.BackColor = System.Drawing.Color.White;
            this.c_correo.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("c_correo.BackgroundImage")));
            this.c_correo.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.c_correo.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.c_correo.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.c_correo.BorderColorIdle = System.Drawing.Color.Silver;
            this.c_correo.BorderRadius = 10;
            this.c_correo.BorderThickness = 2;
            this.c_correo.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.c_correo.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.c_correo.DefaultFont = new System.Drawing.Font("Segoe UI", 9.75F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.c_correo.DefaultText = "";
            this.c_correo.FillColor = System.Drawing.Color.White;
            this.c_correo.HideSelection = true;
            this.c_correo.IconLeft = null;
            this.c_correo.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.c_correo.IconPadding = 10;
            this.c_correo.IconRight = null;
            this.c_correo.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.c_correo.Lines = new string[0];
            this.c_correo.Location = new System.Drawing.Point(605, 186);
            this.c_correo.MaxLength = 32767;
            this.c_correo.MinimumSize = new System.Drawing.Size(1, 1);
            this.c_correo.Modified = false;
            this.c_correo.Multiline = false;
            this.c_correo.Name = "c_correo";
            stateProperties9.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties9.FillColor = System.Drawing.Color.Empty;
            stateProperties9.ForeColor = System.Drawing.Color.Empty;
            stateProperties9.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.c_correo.OnActiveState = stateProperties9;
            stateProperties10.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties10.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties10.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties10.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.c_correo.OnDisabledState = stateProperties10;
            stateProperties11.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties11.FillColor = System.Drawing.Color.Empty;
            stateProperties11.ForeColor = System.Drawing.Color.Empty;
            stateProperties11.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.c_correo.OnHoverState = stateProperties11;
            stateProperties12.BorderColor = System.Drawing.Color.Silver;
            stateProperties12.FillColor = System.Drawing.Color.White;
            stateProperties12.ForeColor = System.Drawing.Color.Empty;
            stateProperties12.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.c_correo.OnIdleState = stateProperties12;
            this.c_correo.Padding = new System.Windows.Forms.Padding(3, 3, 3, 3);
            this.c_correo.PasswordChar = '\0';
            this.c_correo.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.c_correo.PlaceholderText = "Correo @";
            this.c_correo.ReadOnly = false;
            this.c_correo.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.c_correo.SelectedText = "";
            this.c_correo.SelectionLength = 0;
            this.c_correo.SelectionStart = 0;
            this.c_correo.ShortcutsEnabled = true;
            this.c_correo.Size = new System.Drawing.Size(305, 36);
            this.c_correo.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.c_correo.TabIndex = 15;
            this.c_correo.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.c_correo.TextMarginBottom = 0;
            this.c_correo.TextMarginLeft = 3;
            this.c_correo.TextMarginTop = 1;
            this.c_correo.TextPlaceholder = "Correo @";
            this.c_correo.UseSystemPasswordChar = false;
            this.c_correo.WordWrap = true;
            // 
            // c_apellido
            // 
            this.c_apellido.AcceptsReturn = false;
            this.c_apellido.AcceptsTab = false;
            this.c_apellido.AnimationSpeed = 200;
            this.c_apellido.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.c_apellido.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.c_apellido.AutoSizeHeight = true;
            this.c_apellido.BackColor = System.Drawing.Color.White;
            this.c_apellido.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("c_apellido.BackgroundImage")));
            this.c_apellido.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.c_apellido.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.c_apellido.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.c_apellido.BorderColorIdle = System.Drawing.Color.Silver;
            this.c_apellido.BorderRadius = 10;
            this.c_apellido.BorderThickness = 2;
            this.c_apellido.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.c_apellido.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.c_apellido.DefaultFont = new System.Drawing.Font("Segoe UI", 9.75F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.c_apellido.DefaultText = "";
            this.c_apellido.FillColor = System.Drawing.Color.White;
            this.c_apellido.HideSelection = true;
            this.c_apellido.IconLeft = null;
            this.c_apellido.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.c_apellido.IconPadding = 10;
            this.c_apellido.IconRight = null;
            this.c_apellido.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.c_apellido.Lines = new string[0];
            this.c_apellido.Location = new System.Drawing.Point(603, 144);
            this.c_apellido.MaxLength = 32767;
            this.c_apellido.MinimumSize = new System.Drawing.Size(1, 1);
            this.c_apellido.Modified = false;
            this.c_apellido.Multiline = false;
            this.c_apellido.Name = "c_apellido";
            stateProperties13.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties13.FillColor = System.Drawing.Color.Empty;
            stateProperties13.ForeColor = System.Drawing.Color.Empty;
            stateProperties13.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.c_apellido.OnActiveState = stateProperties13;
            stateProperties14.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties14.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties14.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties14.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.c_apellido.OnDisabledState = stateProperties14;
            stateProperties15.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties15.FillColor = System.Drawing.Color.Empty;
            stateProperties15.ForeColor = System.Drawing.Color.Empty;
            stateProperties15.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.c_apellido.OnHoverState = stateProperties15;
            stateProperties16.BorderColor = System.Drawing.Color.Silver;
            stateProperties16.FillColor = System.Drawing.Color.White;
            stateProperties16.ForeColor = System.Drawing.Color.Empty;
            stateProperties16.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.c_apellido.OnIdleState = stateProperties16;
            this.c_apellido.Padding = new System.Windows.Forms.Padding(3, 3, 3, 3);
            this.c_apellido.PasswordChar = '\0';
            this.c_apellido.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.c_apellido.PlaceholderText = "Apellido";
            this.c_apellido.ReadOnly = false;
            this.c_apellido.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.c_apellido.SelectedText = "";
            this.c_apellido.SelectionLength = 0;
            this.c_apellido.SelectionStart = 0;
            this.c_apellido.ShortcutsEnabled = true;
            this.c_apellido.Size = new System.Drawing.Size(305, 36);
            this.c_apellido.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.c_apellido.TabIndex = 14;
            this.c_apellido.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.c_apellido.TextMarginBottom = 0;
            this.c_apellido.TextMarginLeft = 3;
            this.c_apellido.TextMarginTop = 1;
            this.c_apellido.TextPlaceholder = "Apellido";
            this.c_apellido.UseSystemPasswordChar = false;
            this.c_apellido.WordWrap = true;
            // 
            // C_nombre
            // 
            this.C_nombre.AcceptsReturn = false;
            this.C_nombre.AcceptsTab = false;
            this.C_nombre.AnimationSpeed = 200;
            this.C_nombre.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.C_nombre.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.C_nombre.AutoSizeHeight = true;
            this.C_nombre.BackColor = System.Drawing.Color.White;
            this.C_nombre.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("C_nombre.BackgroundImage")));
            this.C_nombre.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.C_nombre.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.C_nombre.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.C_nombre.BorderColorIdle = System.Drawing.Color.Silver;
            this.C_nombre.BorderRadius = 10;
            this.C_nombre.BorderThickness = 2;
            this.C_nombre.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.C_nombre.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.C_nombre.DefaultFont = new System.Drawing.Font("Segoe UI", 9.75F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.C_nombre.DefaultText = "";
            this.C_nombre.FillColor = System.Drawing.Color.White;
            this.C_nombre.HideSelection = true;
            this.C_nombre.IconLeft = null;
            this.C_nombre.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.C_nombre.IconPadding = 10;
            this.C_nombre.IconRight = null;
            this.C_nombre.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.C_nombre.Lines = new string[0];
            this.C_nombre.Location = new System.Drawing.Point(603, 102);
            this.C_nombre.MaxLength = 32767;
            this.C_nombre.MinimumSize = new System.Drawing.Size(1, 1);
            this.C_nombre.Modified = false;
            this.C_nombre.Multiline = false;
            this.C_nombre.Name = "C_nombre";
            stateProperties17.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties17.FillColor = System.Drawing.Color.Empty;
            stateProperties17.ForeColor = System.Drawing.Color.Empty;
            stateProperties17.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.C_nombre.OnActiveState = stateProperties17;
            stateProperties18.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties18.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties18.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties18.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.C_nombre.OnDisabledState = stateProperties18;
            stateProperties19.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties19.FillColor = System.Drawing.Color.Empty;
            stateProperties19.ForeColor = System.Drawing.Color.Empty;
            stateProperties19.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.C_nombre.OnHoverState = stateProperties19;
            stateProperties20.BorderColor = System.Drawing.Color.Silver;
            stateProperties20.FillColor = System.Drawing.Color.White;
            stateProperties20.ForeColor = System.Drawing.Color.Empty;
            stateProperties20.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.C_nombre.OnIdleState = stateProperties20;
            this.C_nombre.Padding = new System.Windows.Forms.Padding(3, 3, 3, 3);
            this.C_nombre.PasswordChar = '\0';
            this.C_nombre.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.C_nombre.PlaceholderText = "Nombre";
            this.C_nombre.ReadOnly = false;
            this.C_nombre.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.C_nombre.SelectedText = "";
            this.C_nombre.SelectionLength = 0;
            this.C_nombre.SelectionStart = 0;
            this.C_nombre.ShortcutsEnabled = true;
            this.C_nombre.Size = new System.Drawing.Size(305, 36);
            this.C_nombre.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.C_nombre.TabIndex = 13;
            this.C_nombre.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.C_nombre.TextMarginBottom = 0;
            this.C_nombre.TextMarginLeft = 3;
            this.C_nombre.TextMarginTop = 1;
            this.C_nombre.TextPlaceholder = "Nombre";
            this.C_nombre.UseSystemPasswordChar = false;
            this.C_nombre.WordWrap = true;
            // 
            // bunifuLabel1
            // 
            this.bunifuLabel1.AllowParentOverrides = false;
            this.bunifuLabel1.AutoEllipsis = false;
            this.bunifuLabel1.Cursor = System.Windows.Forms.Cursors.Default;
            this.bunifuLabel1.CursorType = System.Windows.Forms.Cursors.Default;
            this.bunifuLabel1.Font = new System.Drawing.Font("Lucida Fax", 26.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.bunifuLabel1.Location = new System.Drawing.Point(594, 12);
            this.bunifuLabel1.Name = "bunifuLabel1";
            this.bunifuLabel1.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.bunifuLabel1.Size = new System.Drawing.Size(316, 40);
            this.bunifuLabel1.TabIndex = 23;
            this.bunifuLabel1.Text = "Datos a modificar";
            this.bunifuLabel1.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.bunifuLabel1.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // tabla
            // 
            this.tabla.AllowCustomTheming = false;
            this.tabla.AllowUserToAddRows = false;
            this.tabla.AllowUserToDeleteRows = false;
            dataGridViewCellStyle1.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(248)))), ((int)(((byte)(251)))), ((int)(((byte)(255)))));
            dataGridViewCellStyle1.ForeColor = System.Drawing.Color.Black;
            this.tabla.AlternatingRowsDefaultCellStyle = dataGridViewCellStyle1;
            this.tabla.AutoSizeColumnsMode = System.Windows.Forms.DataGridViewAutoSizeColumnsMode.Fill;
            this.tabla.BorderStyle = System.Windows.Forms.BorderStyle.None;
            this.tabla.CellBorderStyle = System.Windows.Forms.DataGridViewCellBorderStyle.SingleHorizontal;
            this.tabla.ColumnHeadersBorderStyle = System.Windows.Forms.DataGridViewHeaderBorderStyle.None;
            dataGridViewCellStyle2.Alignment = System.Windows.Forms.DataGridViewContentAlignment.MiddleLeft;
            dataGridViewCellStyle2.BackColor = System.Drawing.Color.DodgerBlue;
            dataGridViewCellStyle2.Font = new System.Drawing.Font("Segoe UI Semibold", 11.75F, System.Drawing.FontStyle.Bold);
            dataGridViewCellStyle2.ForeColor = System.Drawing.Color.White;
            dataGridViewCellStyle2.SelectionBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(24)))), ((int)(((byte)(115)))), ((int)(((byte)(204)))));
            dataGridViewCellStyle2.SelectionForeColor = System.Drawing.Color.White;
            dataGridViewCellStyle2.WrapMode = System.Windows.Forms.DataGridViewTriState.True;
            this.tabla.ColumnHeadersDefaultCellStyle = dataGridViewCellStyle2;
            this.tabla.ColumnHeadersHeight = 40;
            this.tabla.CurrentTheme.AlternatingRowsStyle.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(248)))), ((int)(((byte)(251)))), ((int)(((byte)(255)))));
            this.tabla.CurrentTheme.AlternatingRowsStyle.Font = new System.Drawing.Font("Segoe UI Semibold", 9.75F, System.Drawing.FontStyle.Bold);
            this.tabla.CurrentTheme.AlternatingRowsStyle.ForeColor = System.Drawing.Color.Black;
            this.tabla.CurrentTheme.AlternatingRowsStyle.SelectionBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(210)))), ((int)(((byte)(232)))), ((int)(((byte)(255)))));
            this.tabla.CurrentTheme.AlternatingRowsStyle.SelectionForeColor = System.Drawing.Color.Black;
            this.tabla.CurrentTheme.BackColor = System.Drawing.Color.White;
            this.tabla.CurrentTheme.GridColor = System.Drawing.Color.FromArgb(((int)(((byte)(221)))), ((int)(((byte)(238)))), ((int)(((byte)(255)))));
            this.tabla.CurrentTheme.HeaderStyle.BackColor = System.Drawing.Color.DodgerBlue;
            this.tabla.CurrentTheme.HeaderStyle.Font = new System.Drawing.Font("Segoe UI Semibold", 11.75F, System.Drawing.FontStyle.Bold);
            this.tabla.CurrentTheme.HeaderStyle.ForeColor = System.Drawing.Color.White;
            this.tabla.CurrentTheme.HeaderStyle.SelectionBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(24)))), ((int)(((byte)(115)))), ((int)(((byte)(204)))));
            this.tabla.CurrentTheme.HeaderStyle.SelectionForeColor = System.Drawing.Color.White;
            this.tabla.CurrentTheme.Name = null;
            this.tabla.CurrentTheme.RowsStyle.BackColor = System.Drawing.Color.White;
            this.tabla.CurrentTheme.RowsStyle.Font = new System.Drawing.Font("Segoe UI Semibold", 9.75F, System.Drawing.FontStyle.Bold);
            this.tabla.CurrentTheme.RowsStyle.ForeColor = System.Drawing.Color.Black;
            this.tabla.CurrentTheme.RowsStyle.SelectionBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(210)))), ((int)(((byte)(232)))), ((int)(((byte)(255)))));
            this.tabla.CurrentTheme.RowsStyle.SelectionForeColor = System.Drawing.Color.Black;
            dataGridViewCellStyle3.Alignment = System.Windows.Forms.DataGridViewContentAlignment.MiddleLeft;
            dataGridViewCellStyle3.BackColor = System.Drawing.Color.White;
            dataGridViewCellStyle3.Font = new System.Drawing.Font("Segoe UI Semibold", 9.75F, System.Drawing.FontStyle.Bold);
            dataGridViewCellStyle3.ForeColor = System.Drawing.Color.Black;
            dataGridViewCellStyle3.SelectionBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(210)))), ((int)(((byte)(232)))), ((int)(((byte)(255)))));
            dataGridViewCellStyle3.SelectionForeColor = System.Drawing.Color.Black;
            dataGridViewCellStyle3.WrapMode = System.Windows.Forms.DataGridViewTriState.False;
            this.tabla.DefaultCellStyle = dataGridViewCellStyle3;
            this.tabla.EnableHeadersVisualStyles = false;
            this.tabla.GridColor = System.Drawing.Color.FromArgb(((int)(((byte)(221)))), ((int)(((byte)(238)))), ((int)(((byte)(255)))));
            this.tabla.HeaderBackColor = System.Drawing.Color.DodgerBlue;
            this.tabla.HeaderBgColor = System.Drawing.Color.Empty;
            this.tabla.HeaderForeColor = System.Drawing.Color.White;
            this.tabla.Location = new System.Drawing.Point(12, 87);
            this.tabla.Name = "tabla";
            this.tabla.ReadOnly = true;
            this.tabla.RowHeadersVisible = false;
            this.tabla.RowTemplate.Height = 40;
            this.tabla.SelectionMode = System.Windows.Forms.DataGridViewSelectionMode.FullRowSelect;
            this.tabla.Size = new System.Drawing.Size(576, 497);
            this.tabla.TabIndex = 24;
            this.tabla.Theme = Bunifu.UI.WinForms.BunifuDataGridView.PresetThemes.Light;
            // 
            // bunifuLabel2
            // 
            this.bunifuLabel2.AllowParentOverrides = false;
            this.bunifuLabel2.AutoEllipsis = false;
            this.bunifuLabel2.CursorType = null;
            this.bunifuLabel2.Font = new System.Drawing.Font("Lucida Fax", 21.75F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.bunifuLabel2.Location = new System.Drawing.Point(12, 34);
            this.bunifuLabel2.Name = "bunifuLabel2";
            this.bunifuLabel2.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.bunifuLabel2.Size = new System.Drawing.Size(96, 33);
            this.bunifuLabel2.TabIndex = 25;
            this.bunifuLabel2.Text = "Search";
            this.bunifuLabel2.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.bunifuLabel2.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            this.bunifuLabel2.Click += new System.EventHandler(this.bunifuLabel2_Click);
            // 
            // search
            // 
            this.search.AcceptsReturn = false;
            this.search.AcceptsTab = false;
            this.search.AnimationSpeed = 200;
            this.search.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.search.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.search.AutoSizeHeight = true;
            this.search.BackColor = System.Drawing.Color.Transparent;
            this.search.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("search.BackgroundImage")));
            this.search.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.search.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.search.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.search.BorderColorIdle = System.Drawing.Color.Silver;
            this.search.BorderRadius = 1;
            this.search.BorderThickness = 1;
            this.search.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.search.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.search.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.search.DefaultText = "";
            this.search.FillColor = System.Drawing.Color.White;
            this.search.HideSelection = true;
            this.search.IconLeft = null;
            this.search.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.search.IconPadding = 10;
            this.search.IconRight = null;
            this.search.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.search.Lines = new string[0];
            this.search.Location = new System.Drawing.Point(114, 34);
            this.search.MaxLength = 32767;
            this.search.MinimumSize = new System.Drawing.Size(1, 1);
            this.search.Modified = false;
            this.search.Multiline = false;
            this.search.Name = "search";
            stateProperties21.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties21.FillColor = System.Drawing.Color.Empty;
            stateProperties21.ForeColor = System.Drawing.Color.Empty;
            stateProperties21.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.search.OnActiveState = stateProperties21;
            stateProperties22.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties22.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties22.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties22.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.search.OnDisabledState = stateProperties22;
            stateProperties23.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties23.FillColor = System.Drawing.Color.Empty;
            stateProperties23.ForeColor = System.Drawing.Color.Empty;
            stateProperties23.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.search.OnHoverState = stateProperties23;
            stateProperties24.BorderColor = System.Drawing.Color.Silver;
            stateProperties24.FillColor = System.Drawing.Color.White;
            stateProperties24.ForeColor = System.Drawing.Color.Empty;
            stateProperties24.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.search.OnIdleState = stateProperties24;
            this.search.Padding = new System.Windows.Forms.Padding(3, 3, 3, 3);
            this.search.PasswordChar = '\0';
            this.search.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.search.PlaceholderText = "Enter text";
            this.search.ReadOnly = false;
            this.search.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.search.SelectedText = "";
            this.search.SelectionLength = 0;
            this.search.SelectionStart = 0;
            this.search.ShortcutsEnabled = true;
            this.search.Size = new System.Drawing.Size(260, 39);
            this.search.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.search.TabIndex = 26;
            this.search.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.search.TextMarginBottom = 0;
            this.search.TextMarginLeft = 3;
            this.search.TextMarginTop = 1;
            this.search.TextPlaceholder = "Enter text";
            this.search.UseSystemPasswordChar = false;
            this.search.WordWrap = true;
            // 
            // button_search
            // 
            this.button_search.AllowAnimations = true;
            this.button_search.AllowMouseEffects = true;
            this.button_search.AllowToggling = false;
            this.button_search.AnimationSpeed = 200;
            this.button_search.AutoGenerateColors = false;
            this.button_search.AutoRoundBorders = false;
            this.button_search.AutoSizeLeftIcon = true;
            this.button_search.AutoSizeRightIcon = true;
            this.button_search.BackColor = System.Drawing.Color.Transparent;
            this.button_search.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(51)))), ((int)(((byte)(122)))), ((int)(((byte)(183)))));
            this.button_search.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("button_search.BackgroundImage")));
            this.button_search.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.button_search.ButtonText = "Search";
            this.button_search.ButtonTextMarginLeft = 0;
            this.button_search.ColorContrastOnClick = 45;
            this.button_search.ColorContrastOnHover = 45;
            this.button_search.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges1.BottomLeft = true;
            borderEdges1.BottomRight = true;
            borderEdges1.TopLeft = true;
            borderEdges1.TopRight = true;
            this.button_search.CustomizableEdges = borderEdges1;
            this.button_search.DialogResult = System.Windows.Forms.DialogResult.None;
            this.button_search.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.button_search.DisabledFillColor = System.Drawing.Color.Empty;
            this.button_search.DisabledForecolor = System.Drawing.Color.Empty;
            this.button_search.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.button_search.Font = new System.Drawing.Font("Lucida Fax", 18F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.button_search.ForeColor = System.Drawing.Color.White;
            this.button_search.IconLeft = null;
            this.button_search.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.button_search.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.button_search.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.button_search.IconMarginLeft = 11;
            this.button_search.IconPadding = 10;
            this.button_search.IconRight = null;
            this.button_search.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.button_search.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.button_search.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.button_search.IconSize = 25;
            this.button_search.IdleBorderColor = System.Drawing.Color.Empty;
            this.button_search.IdleBorderRadius = 0;
            this.button_search.IdleBorderThickness = 0;
            this.button_search.IdleFillColor = System.Drawing.Color.Empty;
            this.button_search.IdleIconLeftImage = null;
            this.button_search.IdleIconRightImage = null;
            this.button_search.IndicateFocus = false;
            this.button_search.Location = new System.Drawing.Point(380, 34);
            this.button_search.Name = "button_search";
            this.button_search.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.button_search.OnDisabledState.BorderRadius = 1;
            this.button_search.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.button_search.OnDisabledState.BorderThickness = 1;
            this.button_search.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.button_search.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.button_search.OnDisabledState.IconLeftImage = null;
            this.button_search.OnDisabledState.IconRightImage = null;
            this.button_search.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(30)))), ((int)(((byte)(150)))), ((int)(((byte)(255)))));
            this.button_search.onHoverState.BorderRadius = 1;
            this.button_search.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.button_search.onHoverState.BorderThickness = 1;
            this.button_search.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(30)))), ((int)(((byte)(150)))), ((int)(((byte)(255)))));
            this.button_search.onHoverState.ForeColor = System.Drawing.Color.White;
            this.button_search.onHoverState.IconLeftImage = null;
            this.button_search.onHoverState.IconRightImage = null;
            this.button_search.OnIdleState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(2)))), ((int)(((byte)(56)))), ((int)(((byte)(119)))));
            this.button_search.OnIdleState.BorderRadius = 1;
            this.button_search.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.button_search.OnIdleState.BorderThickness = 1;
            this.button_search.OnIdleState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(2)))), ((int)(((byte)(56)))), ((int)(((byte)(119)))));
            this.button_search.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.button_search.OnIdleState.IconLeftImage = null;
            this.button_search.OnIdleState.IconRightImage = null;
            this.button_search.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.button_search.OnPressedState.BorderRadius = 1;
            this.button_search.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.button_search.OnPressedState.BorderThickness = 1;
            this.button_search.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.button_search.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.button_search.OnPressedState.IconLeftImage = null;
            this.button_search.OnPressedState.IconRightImage = null;
            this.button_search.Size = new System.Drawing.Size(129, 39);
            this.button_search.TabIndex = 32;
            this.button_search.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.button_search.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.button_search.TextMarginLeft = 0;
            this.button_search.TextPadding = new System.Windows.Forms.Padding(0);
            this.button_search.UseDefaultRadiusAndThickness = true;
            this.button_search.Click += new System.EventHandler(this.button_search_Click);
            // 
            // Safe
            // 
            this.Safe.AllowAnimations = true;
            this.Safe.AllowMouseEffects = true;
            this.Safe.AllowToggling = false;
            this.Safe.AnimationSpeed = 200;
            this.Safe.AutoGenerateColors = false;
            this.Safe.AutoRoundBorders = false;
            this.Safe.AutoSizeLeftIcon = true;
            this.Safe.AutoSizeRightIcon = true;
            this.Safe.BackColor = System.Drawing.Color.Transparent;
            this.Safe.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(51)))), ((int)(((byte)(122)))), ((int)(((byte)(183)))));
            this.Safe.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("Safe.BackgroundImage")));
            this.Safe.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.Safe.ButtonText = "Safe";
            this.Safe.ButtonTextMarginLeft = 0;
            this.Safe.ColorContrastOnClick = 45;
            this.Safe.ColorContrastOnHover = 45;
            this.Safe.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges2.BottomLeft = true;
            borderEdges2.BottomRight = true;
            borderEdges2.TopLeft = true;
            borderEdges2.TopRight = true;
            this.Safe.CustomizableEdges = borderEdges2;
            this.Safe.DialogResult = System.Windows.Forms.DialogResult.None;
            this.Safe.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.Safe.DisabledFillColor = System.Drawing.Color.Empty;
            this.Safe.DisabledForecolor = System.Drawing.Color.Empty;
            this.Safe.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.Safe.Font = new System.Drawing.Font("Lucida Fax", 18F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.Safe.ForeColor = System.Drawing.Color.White;
            this.Safe.IconLeft = null;
            this.Safe.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.Safe.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.Safe.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.Safe.IconMarginLeft = 11;
            this.Safe.IconPadding = 10;
            this.Safe.IconRight = null;
            this.Safe.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.Safe.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.Safe.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.Safe.IconSize = 25;
            this.Safe.IdleBorderColor = System.Drawing.Color.Empty;
            this.Safe.IdleBorderRadius = 0;
            this.Safe.IdleBorderThickness = 0;
            this.Safe.IdleFillColor = System.Drawing.Color.Empty;
            this.Safe.IdleIconLeftImage = null;
            this.Safe.IdleIconRightImage = null;
            this.Safe.IndicateFocus = false;
            this.Safe.Location = new System.Drawing.Point(605, 543);
            this.Safe.Name = "Safe";
            this.Safe.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.Safe.OnDisabledState.BorderRadius = 1;
            this.Safe.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.Safe.OnDisabledState.BorderThickness = 1;
            this.Safe.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.Safe.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.Safe.OnDisabledState.IconLeftImage = null;
            this.Safe.OnDisabledState.IconRightImage = null;
            this.Safe.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(30)))), ((int)(((byte)(150)))), ((int)(((byte)(255)))));
            this.Safe.onHoverState.BorderRadius = 1;
            this.Safe.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.Safe.onHoverState.BorderThickness = 1;
            this.Safe.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(30)))), ((int)(((byte)(150)))), ((int)(((byte)(255)))));
            this.Safe.onHoverState.ForeColor = System.Drawing.Color.White;
            this.Safe.onHoverState.IconLeftImage = null;
            this.Safe.onHoverState.IconRightImage = null;
            this.Safe.OnIdleState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(2)))), ((int)(((byte)(56)))), ((int)(((byte)(119)))));
            this.Safe.OnIdleState.BorderRadius = 1;
            this.Safe.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.Safe.OnIdleState.BorderThickness = 1;
            this.Safe.OnIdleState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(2)))), ((int)(((byte)(56)))), ((int)(((byte)(119)))));
            this.Safe.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.Safe.OnIdleState.IconLeftImage = null;
            this.Safe.OnIdleState.IconRightImage = null;
            this.Safe.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.Safe.OnPressedState.BorderRadius = 1;
            this.Safe.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.Safe.OnPressedState.BorderThickness = 1;
            this.Safe.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.Safe.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.Safe.OnPressedState.IconLeftImage = null;
            this.Safe.OnPressedState.IconRightImage = null;
            this.Safe.Size = new System.Drawing.Size(303, 39);
            this.Safe.TabIndex = 33;
            this.Safe.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.Safe.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.Safe.TextMarginLeft = 0;
            this.Safe.TextPadding = new System.Windows.Forms.Padding(0);
            this.Safe.UseDefaultRadiusAndThickness = true;
            this.Safe.Click += new System.EventHandler(this.Safe_Click);
            // 
            // codigo
            // 
            this.codigo.AcceptsReturn = false;
            this.codigo.AcceptsTab = false;
            this.codigo.AnimationSpeed = 200;
            this.codigo.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.codigo.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.codigo.AutoSizeHeight = true;
            this.codigo.BackColor = System.Drawing.Color.White;
            this.codigo.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("codigo.BackgroundImage")));
            this.codigo.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.codigo.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.codigo.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.codigo.BorderColorIdle = System.Drawing.Color.Silver;
            this.codigo.BorderRadius = 10;
            this.codigo.BorderThickness = 2;
            this.codigo.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.codigo.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.codigo.DefaultFont = new System.Drawing.Font("Segoe UI", 9.75F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.codigo.DefaultText = "";
            this.codigo.FillColor = System.Drawing.Color.White;
            this.codigo.HideSelection = true;
            this.codigo.IconLeft = null;
            this.codigo.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.codigo.IconPadding = 10;
            this.codigo.IconRight = null;
            this.codigo.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.codigo.Lines = new string[0];
            this.codigo.Location = new System.Drawing.Point(603, 58);
            this.codigo.MaxLength = 32767;
            this.codigo.MinimumSize = new System.Drawing.Size(1, 1);
            this.codigo.Modified = false;
            this.codigo.Multiline = false;
            this.codigo.Name = "codigo";
            stateProperties25.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties25.FillColor = System.Drawing.Color.Empty;
            stateProperties25.ForeColor = System.Drawing.Color.Empty;
            stateProperties25.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.codigo.OnActiveState = stateProperties25;
            stateProperties26.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties26.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties26.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties26.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.codigo.OnDisabledState = stateProperties26;
            stateProperties27.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties27.FillColor = System.Drawing.Color.Empty;
            stateProperties27.ForeColor = System.Drawing.Color.Empty;
            stateProperties27.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.codigo.OnHoverState = stateProperties27;
            stateProperties28.BorderColor = System.Drawing.Color.Silver;
            stateProperties28.FillColor = System.Drawing.Color.White;
            stateProperties28.ForeColor = System.Drawing.Color.Empty;
            stateProperties28.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.codigo.OnIdleState = stateProperties28;
            this.codigo.Padding = new System.Windows.Forms.Padding(3);
            this.codigo.PasswordChar = '\0';
            this.codigo.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.codigo.PlaceholderText = "codigo";
            this.codigo.ReadOnly = false;
            this.codigo.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.codigo.SelectedText = "";
            this.codigo.SelectionLength = 0;
            this.codigo.SelectionStart = 0;
            this.codigo.ShortcutsEnabled = true;
            this.codigo.Size = new System.Drawing.Size(305, 36);
            this.codigo.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.codigo.TabIndex = 34;
            this.codigo.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.codigo.TextMarginBottom = 0;
            this.codigo.TextMarginLeft = 3;
            this.codigo.TextMarginTop = 1;
            this.codigo.TextPlaceholder = "codigo";
            this.codigo.UseSystemPasswordChar = false;
            this.codigo.WordWrap = true;
            // 
            // MOD_VISITAS
            // 
            this.AutoScaleDimensions = new System.Drawing.SizeF(6F, 13F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.ClientSize = new System.Drawing.Size(922, 596);
            this.Controls.Add(this.codigo);
            this.Controls.Add(this.Safe);
            this.Controls.Add(this.button_search);
            this.Controls.Add(this.search);
            this.Controls.Add(this.bunifuLabel2);
            this.Controls.Add(this.tabla);
            this.Controls.Add(this.bunifuLabel1);
            this.Controls.Add(this.Mod_visitor);
            this.Controls.Add(this.c_aula);
            this.Controls.Add(this.carrera_TextBox1);
            this.Controls.Add(this.mot_TextBox1);
            this.Controls.Add(this.Sal_DatePicker1);
            this.Controls.Add(this.Ent_DatePicker1);
            this.Controls.Add(this.c_edificio);
            this.Controls.Add(this.c_correo);
            this.Controls.Add(this.c_apellido);
            this.Controls.Add(this.C_nombre);
            this.FormBorderStyle = System.Windows.Forms.FormBorderStyle.None;
            this.Name = "MOD_VISITAS";
            this.Text = "MOD_VISITAS";
            this.Load += new System.EventHandler(this.MOD_VISITAS_Load);
            ((System.ComponentModel.ISupportInitialize)(this.tabla)).EndInit();
            this.ResumeLayout(false);
            this.PerformLayout();

        }

        #endregion

        private Bunifu.Framework.UI.BunifuThinButton2 Mod_visitor;
        private Bunifu.UI.WinForms.BunifuDropdown c_aula;
        private Bunifu.UI.WinForms.BunifuTextBox carrera_TextBox1;
        private Bunifu.UI.WinForms.BunifuTextBox mot_TextBox1;
        private Bunifu.UI.WinForms.BunifuDatePicker Sal_DatePicker1;
        private Bunifu.UI.WinForms.BunifuDatePicker Ent_DatePicker1;
        private Bunifu.UI.WinForms.BunifuDropdown c_edificio;
        private Bunifu.UI.WinForms.BunifuTextBox c_correo;
        private Bunifu.UI.WinForms.BunifuTextBox c_apellido;
        private Bunifu.UI.WinForms.BunifuTextBox C_nombre;
        private Bunifu.UI.WinForms.BunifuLabel bunifuLabel1;
        private Bunifu.UI.WinForms.BunifuDataGridView tabla;
        private Bunifu.UI.WinForms.BunifuLabel bunifuLabel2;
        private Bunifu.UI.WinForms.BunifuTextBox search;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton button_search;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton Safe;
        private Bunifu.UI.WinForms.BunifuTextBox codigo;
    }
}