
namespace Final_project
{
    partial class USER_FORM
    {
        /// <summary>
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary>
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

        /// <summary>
        /// Required method for Designer support - do not modify
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            System.Windows.Forms.DataGridViewCellStyle dataGridViewCellStyle1 = new System.Windows.Forms.DataGridViewCellStyle();
            System.Windows.Forms.DataGridViewCellStyle dataGridViewCellStyle2 = new System.Windows.Forms.DataGridViewCellStyle();
            System.Windows.Forms.DataGridViewCellStyle dataGridViewCellStyle3 = new System.Windows.Forms.DataGridViewCellStyle();
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(USER_FORM));
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties1 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties2 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties3 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties4 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties5 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties6 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties7 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties8 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties9 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties10 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties11 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties12 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties13 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties14 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties15 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties16 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties17 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties18 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties19 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties20 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges1 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges2 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges3 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges4 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties21 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties22 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties23 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties24 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties25 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties26 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties27 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties28 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            this.tabla = new Bunifu.UI.WinForms.BunifuDataGridView();
            this.date = new Bunifu.UI.WinForms.BunifuDatePicker();
            this.Contra_input = new Bunifu.UI.WinForms.BunifuTextBox();
            this.Tipo_usuario_input = new Bunifu.UI.WinForms.BunifuTextBox();
            this.Usuario_input = new Bunifu.UI.WinForms.BunifuTextBox();
            this.bunifuPanel1 = new Bunifu.UI.WinForms.BunifuPanel();
            this.Apellido_input = new Bunifu.UI.WinForms.BunifuTextBox();
            this.bunifuLabel1 = new Bunifu.UI.WinForms.BunifuLabel();
            this.buscar = new Bunifu.UI.WinForms.BunifuTextBox();
            this.bunifuPictureBox2 = new Bunifu.UI.WinForms.BunifuPictureBox();
            this.btn_nuevo = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.btn_editar = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.btn_eliminar = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.btn_guardar = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.cod_input = new Bunifu.UI.WinForms.BunifuTextBox();
            this.nombre_input = new Bunifu.UI.WinForms.BunifuTextBox();
            ((System.ComponentModel.ISupportInitialize)(this.tabla)).BeginInit();
            this.bunifuPanel1.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)(this.bunifuPictureBox2)).BeginInit();
            this.SuspendLayout();
            // 
            // tabla
            // 
            this.tabla.AllowCustomTheming = false;
            this.tabla.AllowUserToDeleteRows = false;
            dataGridViewCellStyle1.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(44)))), ((int)(((byte)(48)))), ((int)(((byte)(52)))));
            dataGridViewCellStyle1.ForeColor = System.Drawing.Color.White;
            this.tabla.AlternatingRowsDefaultCellStyle = dataGridViewCellStyle1;
            this.tabla.AutoSizeColumnsMode = System.Windows.Forms.DataGridViewAutoSizeColumnsMode.Fill;
            this.tabla.BorderStyle = System.Windows.Forms.BorderStyle.None;
            this.tabla.CellBorderStyle = System.Windows.Forms.DataGridViewCellBorderStyle.SingleHorizontal;
            this.tabla.ColumnHeadersBorderStyle = System.Windows.Forms.DataGridViewHeaderBorderStyle.None;
            dataGridViewCellStyle2.Alignment = System.Windows.Forms.DataGridViewContentAlignment.MiddleLeft;
            dataGridViewCellStyle2.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(15)))), ((int)(((byte)(16)))), ((int)(((byte)(18)))));
            dataGridViewCellStyle2.Font = new System.Drawing.Font("Segoe UI Semibold", 11.75F, System.Drawing.FontStyle.Bold);
            dataGridViewCellStyle2.ForeColor = System.Drawing.Color.White;
            dataGridViewCellStyle2.SelectionBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(63)))), ((int)(((byte)(63)))), ((int)(((byte)(65)))));
            dataGridViewCellStyle2.SelectionForeColor = System.Drawing.Color.White;
            dataGridViewCellStyle2.WrapMode = System.Windows.Forms.DataGridViewTriState.True;
            this.tabla.ColumnHeadersDefaultCellStyle = dataGridViewCellStyle2;
            this.tabla.ColumnHeadersHeight = 40;
            this.tabla.CurrentTheme.AlternatingRowsStyle.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(44)))), ((int)(((byte)(48)))), ((int)(((byte)(52)))));
            this.tabla.CurrentTheme.AlternatingRowsStyle.Font = new System.Drawing.Font("Segoe UI Semibold", 9.75F, System.Drawing.FontStyle.Bold);
            this.tabla.CurrentTheme.AlternatingRowsStyle.ForeColor = System.Drawing.Color.White;
            this.tabla.CurrentTheme.AlternatingRowsStyle.SelectionBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(114)))), ((int)(((byte)(117)))), ((int)(((byte)(119)))));
            this.tabla.CurrentTheme.AlternatingRowsStyle.SelectionForeColor = System.Drawing.Color.WhiteSmoke;
            this.tabla.CurrentTheme.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(15)))), ((int)(((byte)(16)))), ((int)(((byte)(18)))));
            this.tabla.CurrentTheme.GridColor = System.Drawing.Color.FromArgb(((int)(((byte)(50)))), ((int)(((byte)(56)))), ((int)(((byte)(62)))));
            this.tabla.CurrentTheme.HeaderStyle.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(15)))), ((int)(((byte)(16)))), ((int)(((byte)(18)))));
            this.tabla.CurrentTheme.HeaderStyle.Font = new System.Drawing.Font("Segoe UI Semibold", 11.75F, System.Drawing.FontStyle.Bold);
            this.tabla.CurrentTheme.HeaderStyle.ForeColor = System.Drawing.Color.White;
            this.tabla.CurrentTheme.HeaderStyle.SelectionBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(63)))), ((int)(((byte)(63)))), ((int)(((byte)(65)))));
            this.tabla.CurrentTheme.HeaderStyle.SelectionForeColor = System.Drawing.Color.White;
            this.tabla.CurrentTheme.Name = null;
            this.tabla.CurrentTheme.RowsStyle.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(33)))), ((int)(((byte)(37)))), ((int)(((byte)(41)))));
            this.tabla.CurrentTheme.RowsStyle.Font = new System.Drawing.Font("Segoe UI Semibold", 9.75F, System.Drawing.FontStyle.Bold);
            this.tabla.CurrentTheme.RowsStyle.ForeColor = System.Drawing.Color.White;
            this.tabla.CurrentTheme.RowsStyle.SelectionBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(114)))), ((int)(((byte)(117)))), ((int)(((byte)(119)))));
            this.tabla.CurrentTheme.RowsStyle.SelectionForeColor = System.Drawing.Color.WhiteSmoke;
            dataGridViewCellStyle3.Alignment = System.Windows.Forms.DataGridViewContentAlignment.MiddleLeft;
            dataGridViewCellStyle3.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(33)))), ((int)(((byte)(37)))), ((int)(((byte)(41)))));
            dataGridViewCellStyle3.Font = new System.Drawing.Font("Segoe UI Semibold", 9.75F, System.Drawing.FontStyle.Bold);
            dataGridViewCellStyle3.ForeColor = System.Drawing.Color.White;
            dataGridViewCellStyle3.SelectionBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(114)))), ((int)(((byte)(117)))), ((int)(((byte)(119)))));
            dataGridViewCellStyle3.SelectionForeColor = System.Drawing.Color.WhiteSmoke;
            dataGridViewCellStyle3.WrapMode = System.Windows.Forms.DataGridViewTriState.False;
            this.tabla.DefaultCellStyle = dataGridViewCellStyle3;
            this.tabla.EnableHeadersVisualStyles = false;
            this.tabla.GridColor = System.Drawing.Color.FromArgb(((int)(((byte)(50)))), ((int)(((byte)(56)))), ((int)(((byte)(62)))));
            this.tabla.HeaderBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(15)))), ((int)(((byte)(16)))), ((int)(((byte)(18)))));
            this.tabla.HeaderBgColor = System.Drawing.Color.Empty;
            this.tabla.HeaderForeColor = System.Drawing.Color.White;
            this.tabla.Location = new System.Drawing.Point(12, 131);
            this.tabla.Name = "tabla";
            this.tabla.ReadOnly = true;
            this.tabla.RowHeadersVisible = false;
            this.tabla.RowTemplate.Height = 40;
            this.tabla.SelectionMode = System.Windows.Forms.DataGridViewSelectionMode.FullRowSelect;
            this.tabla.Size = new System.Drawing.Size(632, 392);
            this.tabla.TabIndex = 17;
            this.tabla.Theme = Bunifu.UI.WinForms.BunifuDataGridView.PresetThemes.Dark;
            // 
            // date
            // 
            this.date.BackColor = System.Drawing.Color.Transparent;
            this.date.BorderColor = System.Drawing.Color.Silver;
            this.date.BorderRadius = 1;
            this.date.Color = System.Drawing.Color.Silver;
            this.date.DateBorderThickness = Bunifu.UI.WinForms.BunifuDatePicker.BorderThickness.Thin;
            this.date.DateTextAlign = Bunifu.UI.WinForms.BunifuDatePicker.TextAlign.Left;
            this.date.DisabledColor = System.Drawing.Color.Gray;
            this.date.DisplayWeekNumbers = false;
            this.date.DPHeight = 0;
            this.date.DropDownAlign = System.Windows.Forms.LeftRightAlignment.Right;
            this.date.FillDatePicker = false;
            this.date.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.date.ForeColor = System.Drawing.Color.Black;
            this.date.Format = System.Windows.Forms.DateTimePickerFormat.Short;
            this.date.Icon = ((System.Drawing.Image)(resources.GetObject("date.Icon")));
            this.date.IconColor = System.Drawing.Color.Gray;
            this.date.IconLocation = Bunifu.UI.WinForms.BunifuDatePicker.Indicator.Right;
            this.date.LeftTextMargin = 5;
            this.date.Location = new System.Drawing.Point(650, 266);
            this.date.MinimumSize = new System.Drawing.Size(4, 32);
            this.date.Name = "date";
            this.date.Size = new System.Drawing.Size(260, 32);
            this.date.TabIndex = 29;
            // 
            // Contra_input
            // 
            this.Contra_input.AcceptsReturn = false;
            this.Contra_input.AcceptsTab = false;
            this.Contra_input.AnimationSpeed = 200;
            this.Contra_input.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.Contra_input.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.Contra_input.AutoSizeHeight = true;
            this.Contra_input.BackColor = System.Drawing.Color.White;
            this.Contra_input.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("Contra_input.BackgroundImage")));
            this.Contra_input.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.Contra_input.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.Contra_input.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.Contra_input.BorderColorIdle = System.Drawing.Color.Silver;
            this.Contra_input.BorderRadius = 1;
            this.Contra_input.BorderThickness = 1;
            this.Contra_input.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.Contra_input.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.Contra_input.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.Contra_input.DefaultText = "";
            this.Contra_input.FillColor = System.Drawing.Color.White;
            this.Contra_input.HideSelection = true;
            this.Contra_input.IconLeft = null;
            this.Contra_input.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.Contra_input.IconPadding = 10;
            this.Contra_input.IconRight = null;
            this.Contra_input.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.Contra_input.Lines = new string[0];
            this.Contra_input.Location = new System.Drawing.Point(650, 394);
            this.Contra_input.MaxLength = 32767;
            this.Contra_input.MinimumSize = new System.Drawing.Size(1, 1);
            this.Contra_input.Modified = false;
            this.Contra_input.Multiline = false;
            this.Contra_input.Name = "Contra_input";
            stateProperties1.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties1.FillColor = System.Drawing.Color.Empty;
            stateProperties1.ForeColor = System.Drawing.Color.Empty;
            stateProperties1.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.Contra_input.OnActiveState = stateProperties1;
            stateProperties2.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties2.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties2.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties2.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.Contra_input.OnDisabledState = stateProperties2;
            stateProperties3.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties3.FillColor = System.Drawing.Color.Empty;
            stateProperties3.ForeColor = System.Drawing.Color.Empty;
            stateProperties3.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.Contra_input.OnHoverState = stateProperties3;
            stateProperties4.BorderColor = System.Drawing.Color.Silver;
            stateProperties4.FillColor = System.Drawing.Color.White;
            stateProperties4.ForeColor = System.Drawing.Color.Empty;
            stateProperties4.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.Contra_input.OnIdleState = stateProperties4;
            this.Contra_input.Padding = new System.Windows.Forms.Padding(3);
            this.Contra_input.PasswordChar = '\0';
            this.Contra_input.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.Contra_input.PlaceholderText = "Contrasena";
            this.Contra_input.ReadOnly = false;
            this.Contra_input.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.Contra_input.SelectedText = "";
            this.Contra_input.SelectionLength = 0;
            this.Contra_input.SelectionStart = 0;
            this.Contra_input.ShortcutsEnabled = true;
            this.Contra_input.Size = new System.Drawing.Size(260, 39);
            this.Contra_input.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Material;
            this.Contra_input.TabIndex = 28;
            this.Contra_input.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.Contra_input.TextMarginBottom = 0;
            this.Contra_input.TextMarginLeft = 3;
            this.Contra_input.TextMarginTop = 1;
            this.Contra_input.TextPlaceholder = "Contrasena";
            this.Contra_input.UseSystemPasswordChar = false;
            this.Contra_input.WordWrap = true;
            // 
            // Tipo_usuario_input
            // 
            this.Tipo_usuario_input.AcceptsReturn = false;
            this.Tipo_usuario_input.AcceptsTab = false;
            this.Tipo_usuario_input.AnimationSpeed = 200;
            this.Tipo_usuario_input.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.Tipo_usuario_input.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.Tipo_usuario_input.AutoSizeHeight = true;
            this.Tipo_usuario_input.BackColor = System.Drawing.Color.White;
            this.Tipo_usuario_input.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("Tipo_usuario_input.BackgroundImage")));
            this.Tipo_usuario_input.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.Tipo_usuario_input.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.Tipo_usuario_input.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.Tipo_usuario_input.BorderColorIdle = System.Drawing.Color.Silver;
            this.Tipo_usuario_input.BorderRadius = 1;
            this.Tipo_usuario_input.BorderThickness = 1;
            this.Tipo_usuario_input.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.Tipo_usuario_input.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.Tipo_usuario_input.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.Tipo_usuario_input.DefaultText = "";
            this.Tipo_usuario_input.FillColor = System.Drawing.Color.White;
            this.Tipo_usuario_input.HideSelection = true;
            this.Tipo_usuario_input.IconLeft = null;
            this.Tipo_usuario_input.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.Tipo_usuario_input.IconPadding = 10;
            this.Tipo_usuario_input.IconRight = null;
            this.Tipo_usuario_input.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.Tipo_usuario_input.Lines = new string[0];
            this.Tipo_usuario_input.Location = new System.Drawing.Point(650, 304);
            this.Tipo_usuario_input.MaxLength = 32767;
            this.Tipo_usuario_input.MinimumSize = new System.Drawing.Size(1, 1);
            this.Tipo_usuario_input.Modified = false;
            this.Tipo_usuario_input.Multiline = false;
            this.Tipo_usuario_input.Name = "Tipo_usuario_input";
            stateProperties5.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties5.FillColor = System.Drawing.Color.Empty;
            stateProperties5.ForeColor = System.Drawing.Color.Empty;
            stateProperties5.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.Tipo_usuario_input.OnActiveState = stateProperties5;
            stateProperties6.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties6.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties6.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties6.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.Tipo_usuario_input.OnDisabledState = stateProperties6;
            stateProperties7.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties7.FillColor = System.Drawing.Color.Empty;
            stateProperties7.ForeColor = System.Drawing.Color.Empty;
            stateProperties7.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.Tipo_usuario_input.OnHoverState = stateProperties7;
            stateProperties8.BorderColor = System.Drawing.Color.Silver;
            stateProperties8.FillColor = System.Drawing.Color.White;
            stateProperties8.ForeColor = System.Drawing.Color.Empty;
            stateProperties8.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.Tipo_usuario_input.OnIdleState = stateProperties8;
            this.Tipo_usuario_input.Padding = new System.Windows.Forms.Padding(3);
            this.Tipo_usuario_input.PasswordChar = '\0';
            this.Tipo_usuario_input.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.Tipo_usuario_input.PlaceholderText = "Tipo Usuario";
            this.Tipo_usuario_input.ReadOnly = false;
            this.Tipo_usuario_input.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.Tipo_usuario_input.SelectedText = "";
            this.Tipo_usuario_input.SelectionLength = 0;
            this.Tipo_usuario_input.SelectionStart = 0;
            this.Tipo_usuario_input.ShortcutsEnabled = true;
            this.Tipo_usuario_input.Size = new System.Drawing.Size(260, 39);
            this.Tipo_usuario_input.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Material;
            this.Tipo_usuario_input.TabIndex = 26;
            this.Tipo_usuario_input.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.Tipo_usuario_input.TextMarginBottom = 0;
            this.Tipo_usuario_input.TextMarginLeft = 3;
            this.Tipo_usuario_input.TextMarginTop = 1;
            this.Tipo_usuario_input.TextPlaceholder = "Tipo Usuario";
            this.Tipo_usuario_input.UseSystemPasswordChar = false;
            this.Tipo_usuario_input.WordWrap = true;
            this.Tipo_usuario_input.TextChanged += new System.EventHandler(this.Tipo_usuario_input_TextChanged);
            // 
            // Usuario_input
            // 
            this.Usuario_input.AcceptsReturn = false;
            this.Usuario_input.AcceptsTab = false;
            this.Usuario_input.AnimationSpeed = 200;
            this.Usuario_input.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.Usuario_input.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.Usuario_input.AutoSizeHeight = true;
            this.Usuario_input.BackColor = System.Drawing.Color.White;
            this.Usuario_input.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("Usuario_input.BackgroundImage")));
            this.Usuario_input.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.Usuario_input.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.Usuario_input.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.Usuario_input.BorderColorIdle = System.Drawing.Color.Silver;
            this.Usuario_input.BorderRadius = 1;
            this.Usuario_input.BorderThickness = 1;
            this.Usuario_input.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.Usuario_input.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.Usuario_input.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.Usuario_input.DefaultText = "";
            this.Usuario_input.FillColor = System.Drawing.Color.White;
            this.Usuario_input.HideSelection = true;
            this.Usuario_input.IconLeft = null;
            this.Usuario_input.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.Usuario_input.IconPadding = 10;
            this.Usuario_input.IconRight = null;
            this.Usuario_input.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.Usuario_input.Lines = new string[0];
            this.Usuario_input.Location = new System.Drawing.Point(650, 349);
            this.Usuario_input.MaxLength = 32767;
            this.Usuario_input.MinimumSize = new System.Drawing.Size(1, 1);
            this.Usuario_input.Modified = false;
            this.Usuario_input.Multiline = false;
            this.Usuario_input.Name = "Usuario_input";
            stateProperties9.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties9.FillColor = System.Drawing.Color.Empty;
            stateProperties9.ForeColor = System.Drawing.Color.Empty;
            stateProperties9.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.Usuario_input.OnActiveState = stateProperties9;
            stateProperties10.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties10.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties10.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties10.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.Usuario_input.OnDisabledState = stateProperties10;
            stateProperties11.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties11.FillColor = System.Drawing.Color.Empty;
            stateProperties11.ForeColor = System.Drawing.Color.Empty;
            stateProperties11.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.Usuario_input.OnHoverState = stateProperties11;
            stateProperties12.BorderColor = System.Drawing.Color.Silver;
            stateProperties12.FillColor = System.Drawing.Color.White;
            stateProperties12.ForeColor = System.Drawing.Color.Empty;
            stateProperties12.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.Usuario_input.OnIdleState = stateProperties12;
            this.Usuario_input.Padding = new System.Windows.Forms.Padding(3);
            this.Usuario_input.PasswordChar = '\0';
            this.Usuario_input.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.Usuario_input.PlaceholderText = "Usuario";
            this.Usuario_input.ReadOnly = false;
            this.Usuario_input.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.Usuario_input.SelectedText = "";
            this.Usuario_input.SelectionLength = 0;
            this.Usuario_input.SelectionStart = 0;
            this.Usuario_input.ShortcutsEnabled = true;
            this.Usuario_input.Size = new System.Drawing.Size(260, 39);
            this.Usuario_input.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Material;
            this.Usuario_input.TabIndex = 27;
            this.Usuario_input.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.Usuario_input.TextMarginBottom = 0;
            this.Usuario_input.TextMarginLeft = 3;
            this.Usuario_input.TextMarginTop = 1;
            this.Usuario_input.TextPlaceholder = "Usuario";
            this.Usuario_input.UseSystemPasswordChar = false;
            this.Usuario_input.WordWrap = true;
            // 
            // bunifuPanel1
            // 
            this.bunifuPanel1.BackgroundColor = System.Drawing.Color.FromArgb(((int)(((byte)(228)))), ((int)(((byte)(37)))), ((int)(((byte)(43)))));
            this.bunifuPanel1.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("bunifuPanel1.BackgroundImage")));
            this.bunifuPanel1.BackgroundImageLayout = System.Windows.Forms.ImageLayout.Stretch;
            this.bunifuPanel1.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(228)))), ((int)(((byte)(37)))), ((int)(((byte)(43)))));
            this.bunifuPanel1.BorderRadius = 3;
            this.bunifuPanel1.BorderThickness = 1;
            this.bunifuPanel1.Controls.Add(this.bunifuLabel1);
            this.bunifuPanel1.Dock = System.Windows.Forms.DockStyle.Top;
            this.bunifuPanel1.Location = new System.Drawing.Point(0, 0);
            this.bunifuPanel1.Name = "bunifuPanel1";
            this.bunifuPanel1.ShowBorders = true;
            this.bunifuPanel1.Size = new System.Drawing.Size(922, 67);
            this.bunifuPanel1.TabIndex = 14;
            // 
            // Apellido_input
            // 
            this.Apellido_input.AcceptsReturn = false;
            this.Apellido_input.AcceptsTab = false;
            this.Apellido_input.AnimationSpeed = 200;
            this.Apellido_input.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.Apellido_input.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.Apellido_input.AutoSizeHeight = true;
            this.Apellido_input.BackColor = System.Drawing.Color.White;
            this.Apellido_input.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("Apellido_input.BackgroundImage")));
            this.Apellido_input.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.Apellido_input.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.Apellido_input.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.Apellido_input.BorderColorIdle = System.Drawing.Color.Silver;
            this.Apellido_input.BorderRadius = 1;
            this.Apellido_input.BorderThickness = 1;
            this.Apellido_input.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.Apellido_input.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.Apellido_input.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.Apellido_input.DefaultText = "";
            this.Apellido_input.FillColor = System.Drawing.Color.White;
            this.Apellido_input.HideSelection = true;
            this.Apellido_input.IconLeft = null;
            this.Apellido_input.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.Apellido_input.IconPadding = 10;
            this.Apellido_input.IconRight = null;
            this.Apellido_input.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.Apellido_input.Lines = new string[0];
            this.Apellido_input.Location = new System.Drawing.Point(650, 221);
            this.Apellido_input.MaxLength = 32767;
            this.Apellido_input.MinimumSize = new System.Drawing.Size(1, 1);
            this.Apellido_input.Modified = false;
            this.Apellido_input.Multiline = false;
            this.Apellido_input.Name = "Apellido_input";
            stateProperties13.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties13.FillColor = System.Drawing.Color.Empty;
            stateProperties13.ForeColor = System.Drawing.Color.Empty;
            stateProperties13.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.Apellido_input.OnActiveState = stateProperties13;
            stateProperties14.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties14.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties14.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties14.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.Apellido_input.OnDisabledState = stateProperties14;
            stateProperties15.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties15.FillColor = System.Drawing.Color.Empty;
            stateProperties15.ForeColor = System.Drawing.Color.Empty;
            stateProperties15.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.Apellido_input.OnHoverState = stateProperties15;
            stateProperties16.BorderColor = System.Drawing.Color.Silver;
            stateProperties16.FillColor = System.Drawing.Color.White;
            stateProperties16.ForeColor = System.Drawing.Color.Empty;
            stateProperties16.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.Apellido_input.OnIdleState = stateProperties16;
            this.Apellido_input.Padding = new System.Windows.Forms.Padding(3);
            this.Apellido_input.PasswordChar = '\0';
            this.Apellido_input.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.Apellido_input.PlaceholderText = "Apellido";
            this.Apellido_input.ReadOnly = false;
            this.Apellido_input.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.Apellido_input.SelectedText = "";
            this.Apellido_input.SelectionLength = 0;
            this.Apellido_input.SelectionStart = 0;
            this.Apellido_input.ShortcutsEnabled = true;
            this.Apellido_input.Size = new System.Drawing.Size(260, 39);
            this.Apellido_input.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Material;
            this.Apellido_input.TabIndex = 24;
            this.Apellido_input.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.Apellido_input.TextMarginBottom = 0;
            this.Apellido_input.TextMarginLeft = 3;
            this.Apellido_input.TextMarginTop = 1;
            this.Apellido_input.TextPlaceholder = "Apellido";
            this.Apellido_input.UseSystemPasswordChar = false;
            this.Apellido_input.WordWrap = true;
            // 
            // bunifuLabel1
            // 
            this.bunifuLabel1.AllowParentOverrides = false;
            this.bunifuLabel1.AutoEllipsis = false;
            this.bunifuLabel1.Cursor = System.Windows.Forms.Cursors.Default;
            this.bunifuLabel1.CursorType = System.Windows.Forms.Cursors.Default;
            this.bunifuLabel1.Font = new System.Drawing.Font("Lucida Fax", 24F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.bunifuLabel1.Location = new System.Drawing.Point(12, 12);
            this.bunifuLabel1.Name = "bunifuLabel1";
            this.bunifuLabel1.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.bunifuLabel1.Size = new System.Drawing.Size(356, 37);
            this.bunifuLabel1.TabIndex = 1;
            this.bunifuLabel1.Text = "USUARIOS GENERALES";
            this.bunifuLabel1.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.bunifuLabel1.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // buscar
            // 
            this.buscar.AcceptsReturn = false;
            this.buscar.AcceptsTab = false;
            this.buscar.AnimationSpeed = 200;
            this.buscar.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.buscar.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.buscar.AutoSizeHeight = true;
            this.buscar.BackColor = System.Drawing.Color.White;
            this.buscar.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("buscar.BackgroundImage")));
            this.buscar.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.buscar.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.buscar.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.buscar.BorderColorIdle = System.Drawing.Color.Silver;
            this.buscar.BorderRadius = 1;
            this.buscar.BorderThickness = 1;
            this.buscar.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.buscar.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.buscar.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.buscar.DefaultText = "";
            this.buscar.FillColor = System.Drawing.Color.White;
            this.buscar.HideSelection = true;
            this.buscar.IconLeft = null;
            this.buscar.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.buscar.IconPadding = 10;
            this.buscar.IconRight = null;
            this.buscar.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.buscar.Lines = new string[0];
            this.buscar.Location = new System.Drawing.Point(75, 73);
            this.buscar.MaxLength = 32767;
            this.buscar.MinimumSize = new System.Drawing.Size(1, 1);
            this.buscar.Modified = false;
            this.buscar.Multiline = false;
            this.buscar.Name = "buscar";
            stateProperties17.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties17.FillColor = System.Drawing.Color.Empty;
            stateProperties17.ForeColor = System.Drawing.Color.Empty;
            stateProperties17.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.buscar.OnActiveState = stateProperties17;
            stateProperties18.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties18.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties18.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties18.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.buscar.OnDisabledState = stateProperties18;
            stateProperties19.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties19.FillColor = System.Drawing.Color.Empty;
            stateProperties19.ForeColor = System.Drawing.Color.Empty;
            stateProperties19.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.buscar.OnHoverState = stateProperties19;
            stateProperties20.BorderColor = System.Drawing.Color.Silver;
            stateProperties20.FillColor = System.Drawing.Color.White;
            stateProperties20.ForeColor = System.Drawing.Color.Empty;
            stateProperties20.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.buscar.OnIdleState = stateProperties20;
            this.buscar.Padding = new System.Windows.Forms.Padding(3);
            this.buscar.PasswordChar = '\0';
            this.buscar.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.buscar.PlaceholderText = "Enter text";
            this.buscar.ReadOnly = false;
            this.buscar.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.buscar.SelectedText = "";
            this.buscar.SelectionLength = 0;
            this.buscar.SelectionStart = 0;
            this.buscar.ShortcutsEnabled = true;
            this.buscar.Size = new System.Drawing.Size(260, 39);
            this.buscar.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Material;
            this.buscar.TabIndex = 15;
            this.buscar.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.buscar.TextMarginBottom = 0;
            this.buscar.TextMarginLeft = 3;
            this.buscar.TextMarginTop = 1;
            this.buscar.TextPlaceholder = "Enter text";
            this.buscar.UseSystemPasswordChar = false;
            this.buscar.WordWrap = true;
            this.buscar.TextChanged += new System.EventHandler(this.buscar_TextChanged);
            // 
            // bunifuPictureBox2
            // 
            this.bunifuPictureBox2.AllowFocused = false;
            this.bunifuPictureBox2.Anchor = System.Windows.Forms.AnchorStyles.None;
            this.bunifuPictureBox2.AutoSizeHeight = false;
            this.bunifuPictureBox2.BorderRadius = 0;
            this.bunifuPictureBox2.Image = global::Final_project.Properties.Resources.searchmagnifierinterfacesymbol1_79893;
            this.bunifuPictureBox2.IsCircle = false;
            this.bunifuPictureBox2.Location = new System.Drawing.Point(12, 73);
            this.bunifuPictureBox2.Name = "bunifuPictureBox2";
            this.bunifuPictureBox2.Size = new System.Drawing.Size(43, 39);
            this.bunifuPictureBox2.SizeMode = System.Windows.Forms.PictureBoxSizeMode.Zoom;
            this.bunifuPictureBox2.TabIndex = 16;
            this.bunifuPictureBox2.TabStop = false;
            this.bunifuPictureBox2.Type = Bunifu.UI.WinForms.BunifuPictureBox.Types.Custom;
            // 
            // btn_nuevo
            // 
            this.btn_nuevo.AllowAnimations = true;
            this.btn_nuevo.AllowMouseEffects = true;
            this.btn_nuevo.AllowToggling = false;
            this.btn_nuevo.AnimationSpeed = 200;
            this.btn_nuevo.AutoGenerateColors = false;
            this.btn_nuevo.AutoRoundBorders = false;
            this.btn_nuevo.AutoSizeLeftIcon = true;
            this.btn_nuevo.AutoSizeRightIcon = true;
            this.btn_nuevo.BackColor = System.Drawing.Color.Transparent;
            this.btn_nuevo.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(51)))), ((int)(((byte)(122)))), ((int)(((byte)(183)))));
            this.btn_nuevo.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btn_nuevo.BackgroundImage")));
            this.btn_nuevo.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btn_nuevo.ButtonText = "NUEVO";
            this.btn_nuevo.ButtonTextMarginLeft = 0;
            this.btn_nuevo.ColorContrastOnClick = 45;
            this.btn_nuevo.ColorContrastOnHover = 45;
            this.btn_nuevo.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges1.BottomLeft = true;
            borderEdges1.BottomRight = true;
            borderEdges1.TopLeft = true;
            borderEdges1.TopRight = true;
            this.btn_nuevo.CustomizableEdges = borderEdges1;
            this.btn_nuevo.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btn_nuevo.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btn_nuevo.DisabledFillColor = System.Drawing.Color.Empty;
            this.btn_nuevo.DisabledForecolor = System.Drawing.Color.Empty;
            this.btn_nuevo.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.btn_nuevo.Font = new System.Drawing.Font("Segoe UI", 14.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.btn_nuevo.ForeColor = System.Drawing.Color.White;
            this.btn_nuevo.IconLeft = null;
            this.btn_nuevo.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btn_nuevo.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btn_nuevo.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.btn_nuevo.IconMarginLeft = 11;
            this.btn_nuevo.IconPadding = 10;
            this.btn_nuevo.IconRight = null;
            this.btn_nuevo.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btn_nuevo.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btn_nuevo.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btn_nuevo.IconSize = 25;
            this.btn_nuevo.IdleBorderColor = System.Drawing.Color.Empty;
            this.btn_nuevo.IdleBorderRadius = 0;
            this.btn_nuevo.IdleBorderThickness = 0;
            this.btn_nuevo.IdleFillColor = System.Drawing.Color.Empty;
            this.btn_nuevo.IdleIconLeftImage = null;
            this.btn_nuevo.IdleIconRightImage = null;
            this.btn_nuevo.IndicateFocus = false;
            this.btn_nuevo.Location = new System.Drawing.Point(12, 529);
            this.btn_nuevo.Name = "btn_nuevo";
            this.btn_nuevo.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btn_nuevo.OnDisabledState.BorderRadius = 1;
            this.btn_nuevo.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btn_nuevo.OnDisabledState.BorderThickness = 1;
            this.btn_nuevo.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btn_nuevo.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btn_nuevo.OnDisabledState.IconLeftImage = null;
            this.btn_nuevo.OnDisabledState.IconRightImage = null;
            this.btn_nuevo.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(30)))), ((int)(((byte)(150)))), ((int)(((byte)(255)))));
            this.btn_nuevo.onHoverState.BorderRadius = 1;
            this.btn_nuevo.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btn_nuevo.onHoverState.BorderThickness = 1;
            this.btn_nuevo.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(30)))), ((int)(((byte)(150)))), ((int)(((byte)(255)))));
            this.btn_nuevo.onHoverState.ForeColor = System.Drawing.Color.White;
            this.btn_nuevo.onHoverState.IconLeftImage = null;
            this.btn_nuevo.onHoverState.IconRightImage = null;
            this.btn_nuevo.OnIdleState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(2)))), ((int)(((byte)(56)))), ((int)(((byte)(119)))));
            this.btn_nuevo.OnIdleState.BorderRadius = 1;
            this.btn_nuevo.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btn_nuevo.OnIdleState.BorderThickness = 1;
            this.btn_nuevo.OnIdleState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(2)))), ((int)(((byte)(56)))), ((int)(((byte)(119)))));
            this.btn_nuevo.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.btn_nuevo.OnIdleState.IconLeftImage = null;
            this.btn_nuevo.OnIdleState.IconRightImage = null;
            this.btn_nuevo.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btn_nuevo.OnPressedState.BorderRadius = 1;
            this.btn_nuevo.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btn_nuevo.OnPressedState.BorderThickness = 1;
            this.btn_nuevo.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btn_nuevo.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.btn_nuevo.OnPressedState.IconLeftImage = null;
            this.btn_nuevo.OnPressedState.IconRightImage = null;
            this.btn_nuevo.Size = new System.Drawing.Size(126, 61);
            this.btn_nuevo.TabIndex = 18;
            this.btn_nuevo.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btn_nuevo.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btn_nuevo.TextMarginLeft = 0;
            this.btn_nuevo.TextPadding = new System.Windows.Forms.Padding(0);
            this.btn_nuevo.UseDefaultRadiusAndThickness = true;
            this.btn_nuevo.Click += new System.EventHandler(this.btn_nuevo_Click);
            // 
            // btn_editar
            // 
            this.btn_editar.AllowAnimations = true;
            this.btn_editar.AllowMouseEffects = true;
            this.btn_editar.AllowToggling = false;
            this.btn_editar.AnimationSpeed = 200;
            this.btn_editar.AutoGenerateColors = false;
            this.btn_editar.AutoRoundBorders = false;
            this.btn_editar.AutoSizeLeftIcon = true;
            this.btn_editar.AutoSizeRightIcon = true;
            this.btn_editar.BackColor = System.Drawing.Color.Transparent;
            this.btn_editar.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(51)))), ((int)(((byte)(122)))), ((int)(((byte)(183)))));
            this.btn_editar.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btn_editar.BackgroundImage")));
            this.btn_editar.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btn_editar.ButtonText = "EDITAR";
            this.btn_editar.ButtonTextMarginLeft = 0;
            this.btn_editar.ColorContrastOnClick = 45;
            this.btn_editar.ColorContrastOnHover = 45;
            this.btn_editar.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges2.BottomLeft = true;
            borderEdges2.BottomRight = true;
            borderEdges2.TopLeft = true;
            borderEdges2.TopRight = true;
            this.btn_editar.CustomizableEdges = borderEdges2;
            this.btn_editar.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btn_editar.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btn_editar.DisabledFillColor = System.Drawing.Color.Empty;
            this.btn_editar.DisabledForecolor = System.Drawing.Color.Empty;
            this.btn_editar.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.btn_editar.Font = new System.Drawing.Font("Segoe UI", 14.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.btn_editar.ForeColor = System.Drawing.Color.White;
            this.btn_editar.IconLeft = null;
            this.btn_editar.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btn_editar.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btn_editar.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.btn_editar.IconMarginLeft = 11;
            this.btn_editar.IconPadding = 10;
            this.btn_editar.IconRight = null;
            this.btn_editar.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btn_editar.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btn_editar.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btn_editar.IconSize = 25;
            this.btn_editar.IdleBorderColor = System.Drawing.Color.Empty;
            this.btn_editar.IdleBorderRadius = 0;
            this.btn_editar.IdleBorderThickness = 0;
            this.btn_editar.IdleFillColor = System.Drawing.Color.Empty;
            this.btn_editar.IdleIconLeftImage = null;
            this.btn_editar.IdleIconRightImage = null;
            this.btn_editar.IndicateFocus = false;
            this.btn_editar.Location = new System.Drawing.Point(459, 529);
            this.btn_editar.Name = "btn_editar";
            this.btn_editar.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btn_editar.OnDisabledState.BorderRadius = 1;
            this.btn_editar.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btn_editar.OnDisabledState.BorderThickness = 1;
            this.btn_editar.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btn_editar.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btn_editar.OnDisabledState.IconLeftImage = null;
            this.btn_editar.OnDisabledState.IconRightImage = null;
            this.btn_editar.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(30)))), ((int)(((byte)(150)))), ((int)(((byte)(255)))));
            this.btn_editar.onHoverState.BorderRadius = 1;
            this.btn_editar.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btn_editar.onHoverState.BorderThickness = 1;
            this.btn_editar.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(30)))), ((int)(((byte)(150)))), ((int)(((byte)(255)))));
            this.btn_editar.onHoverState.ForeColor = System.Drawing.Color.White;
            this.btn_editar.onHoverState.IconLeftImage = null;
            this.btn_editar.onHoverState.IconRightImage = null;
            this.btn_editar.OnIdleState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(2)))), ((int)(((byte)(56)))), ((int)(((byte)(119)))));
            this.btn_editar.OnIdleState.BorderRadius = 1;
            this.btn_editar.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btn_editar.OnIdleState.BorderThickness = 1;
            this.btn_editar.OnIdleState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(2)))), ((int)(((byte)(56)))), ((int)(((byte)(119)))));
            this.btn_editar.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.btn_editar.OnIdleState.IconLeftImage = null;
            this.btn_editar.OnIdleState.IconRightImage = null;
            this.btn_editar.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btn_editar.OnPressedState.BorderRadius = 1;
            this.btn_editar.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btn_editar.OnPressedState.BorderThickness = 1;
            this.btn_editar.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btn_editar.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.btn_editar.OnPressedState.IconLeftImage = null;
            this.btn_editar.OnPressedState.IconRightImage = null;
            this.btn_editar.Size = new System.Drawing.Size(126, 61);
            this.btn_editar.TabIndex = 19;
            this.btn_editar.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btn_editar.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btn_editar.TextMarginLeft = 0;
            this.btn_editar.TextPadding = new System.Windows.Forms.Padding(0);
            this.btn_editar.UseDefaultRadiusAndThickness = true;
            this.btn_editar.Click += new System.EventHandler(this.btn_editar_Click);
            // 
            // btn_eliminar
            // 
            this.btn_eliminar.AllowAnimations = true;
            this.btn_eliminar.AllowMouseEffects = true;
            this.btn_eliminar.AllowToggling = false;
            this.btn_eliminar.AnimationSpeed = 200;
            this.btn_eliminar.AutoGenerateColors = false;
            this.btn_eliminar.AutoRoundBorders = false;
            this.btn_eliminar.AutoSizeLeftIcon = true;
            this.btn_eliminar.AutoSizeRightIcon = true;
            this.btn_eliminar.BackColor = System.Drawing.Color.Transparent;
            this.btn_eliminar.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(51)))), ((int)(((byte)(122)))), ((int)(((byte)(183)))));
            this.btn_eliminar.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btn_eliminar.BackgroundImage")));
            this.btn_eliminar.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btn_eliminar.ButtonText = "ELIMINAR";
            this.btn_eliminar.ButtonTextMarginLeft = 0;
            this.btn_eliminar.ColorContrastOnClick = 45;
            this.btn_eliminar.ColorContrastOnHover = 45;
            this.btn_eliminar.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges3.BottomLeft = true;
            borderEdges3.BottomRight = true;
            borderEdges3.TopLeft = true;
            borderEdges3.TopRight = true;
            this.btn_eliminar.CustomizableEdges = borderEdges3;
            this.btn_eliminar.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btn_eliminar.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btn_eliminar.DisabledFillColor = System.Drawing.Color.Empty;
            this.btn_eliminar.DisabledForecolor = System.Drawing.Color.Empty;
            this.btn_eliminar.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.btn_eliminar.Font = new System.Drawing.Font("Segoe UI", 14.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.btn_eliminar.ForeColor = System.Drawing.Color.White;
            this.btn_eliminar.IconLeft = null;
            this.btn_eliminar.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btn_eliminar.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btn_eliminar.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.btn_eliminar.IconMarginLeft = 11;
            this.btn_eliminar.IconPadding = 10;
            this.btn_eliminar.IconRight = null;
            this.btn_eliminar.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btn_eliminar.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btn_eliminar.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btn_eliminar.IconSize = 25;
            this.btn_eliminar.IdleBorderColor = System.Drawing.Color.Empty;
            this.btn_eliminar.IdleBorderRadius = 0;
            this.btn_eliminar.IdleBorderThickness = 0;
            this.btn_eliminar.IdleFillColor = System.Drawing.Color.Empty;
            this.btn_eliminar.IdleIconLeftImage = null;
            this.btn_eliminar.IdleIconRightImage = null;
            this.btn_eliminar.IndicateFocus = false;
            this.btn_eliminar.Location = new System.Drawing.Point(234, 529);
            this.btn_eliminar.Name = "btn_eliminar";
            this.btn_eliminar.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btn_eliminar.OnDisabledState.BorderRadius = 1;
            this.btn_eliminar.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btn_eliminar.OnDisabledState.BorderThickness = 1;
            this.btn_eliminar.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btn_eliminar.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btn_eliminar.OnDisabledState.IconLeftImage = null;
            this.btn_eliminar.OnDisabledState.IconRightImage = null;
            this.btn_eliminar.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(30)))), ((int)(((byte)(150)))), ((int)(((byte)(255)))));
            this.btn_eliminar.onHoverState.BorderRadius = 1;
            this.btn_eliminar.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btn_eliminar.onHoverState.BorderThickness = 1;
            this.btn_eliminar.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(30)))), ((int)(((byte)(150)))), ((int)(((byte)(255)))));
            this.btn_eliminar.onHoverState.ForeColor = System.Drawing.Color.White;
            this.btn_eliminar.onHoverState.IconLeftImage = null;
            this.btn_eliminar.onHoverState.IconRightImage = null;
            this.btn_eliminar.OnIdleState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(2)))), ((int)(((byte)(56)))), ((int)(((byte)(119)))));
            this.btn_eliminar.OnIdleState.BorderRadius = 1;
            this.btn_eliminar.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btn_eliminar.OnIdleState.BorderThickness = 1;
            this.btn_eliminar.OnIdleState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(2)))), ((int)(((byte)(56)))), ((int)(((byte)(119)))));
            this.btn_eliminar.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.btn_eliminar.OnIdleState.IconLeftImage = null;
            this.btn_eliminar.OnIdleState.IconRightImage = null;
            this.btn_eliminar.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btn_eliminar.OnPressedState.BorderRadius = 1;
            this.btn_eliminar.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btn_eliminar.OnPressedState.BorderThickness = 1;
            this.btn_eliminar.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btn_eliminar.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.btn_eliminar.OnPressedState.IconLeftImage = null;
            this.btn_eliminar.OnPressedState.IconRightImage = null;
            this.btn_eliminar.Size = new System.Drawing.Size(126, 61);
            this.btn_eliminar.TabIndex = 20;
            this.btn_eliminar.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btn_eliminar.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btn_eliminar.TextMarginLeft = 0;
            this.btn_eliminar.TextPadding = new System.Windows.Forms.Padding(0);
            this.btn_eliminar.UseDefaultRadiusAndThickness = true;
            this.btn_eliminar.Click += new System.EventHandler(this.btn_eliminar_Click);
            // 
            // btn_guardar
            // 
            this.btn_guardar.AllowAnimations = true;
            this.btn_guardar.AllowMouseEffects = true;
            this.btn_guardar.AllowToggling = false;
            this.btn_guardar.AnimationSpeed = 200;
            this.btn_guardar.AutoGenerateColors = false;
            this.btn_guardar.AutoRoundBorders = false;
            this.btn_guardar.AutoSizeLeftIcon = true;
            this.btn_guardar.AutoSizeRightIcon = true;
            this.btn_guardar.BackColor = System.Drawing.Color.Transparent;
            this.btn_guardar.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(51)))), ((int)(((byte)(122)))), ((int)(((byte)(183)))));
            this.btn_guardar.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btn_guardar.BackgroundImage")));
            this.btn_guardar.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btn_guardar.ButtonText = "GUARDAR";
            this.btn_guardar.ButtonTextMarginLeft = 0;
            this.btn_guardar.ColorContrastOnClick = 45;
            this.btn_guardar.ColorContrastOnHover = 45;
            this.btn_guardar.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges4.BottomLeft = true;
            borderEdges4.BottomRight = true;
            borderEdges4.TopLeft = true;
            borderEdges4.TopRight = true;
            this.btn_guardar.CustomizableEdges = borderEdges4;
            this.btn_guardar.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btn_guardar.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btn_guardar.DisabledFillColor = System.Drawing.Color.Empty;
            this.btn_guardar.DisabledForecolor = System.Drawing.Color.Empty;
            this.btn_guardar.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.btn_guardar.Font = new System.Drawing.Font("Segoe UI", 14.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.btn_guardar.ForeColor = System.Drawing.Color.White;
            this.btn_guardar.IconLeft = null;
            this.btn_guardar.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btn_guardar.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btn_guardar.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.btn_guardar.IconMarginLeft = 11;
            this.btn_guardar.IconPadding = 10;
            this.btn_guardar.IconRight = null;
            this.btn_guardar.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btn_guardar.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btn_guardar.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btn_guardar.IconSize = 25;
            this.btn_guardar.IdleBorderColor = System.Drawing.Color.Empty;
            this.btn_guardar.IdleBorderRadius = 0;
            this.btn_guardar.IdleBorderThickness = 0;
            this.btn_guardar.IdleFillColor = System.Drawing.Color.Empty;
            this.btn_guardar.IdleIconLeftImage = null;
            this.btn_guardar.IdleIconRightImage = null;
            this.btn_guardar.IndicateFocus = false;
            this.btn_guardar.Location = new System.Drawing.Point(650, 446);
            this.btn_guardar.Name = "btn_guardar";
            this.btn_guardar.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btn_guardar.OnDisabledState.BorderRadius = 1;
            this.btn_guardar.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btn_guardar.OnDisabledState.BorderThickness = 1;
            this.btn_guardar.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btn_guardar.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btn_guardar.OnDisabledState.IconLeftImage = null;
            this.btn_guardar.OnDisabledState.IconRightImage = null;
            this.btn_guardar.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(30)))), ((int)(((byte)(150)))), ((int)(((byte)(255)))));
            this.btn_guardar.onHoverState.BorderRadius = 1;
            this.btn_guardar.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btn_guardar.onHoverState.BorderThickness = 1;
            this.btn_guardar.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(30)))), ((int)(((byte)(150)))), ((int)(((byte)(255)))));
            this.btn_guardar.onHoverState.ForeColor = System.Drawing.Color.White;
            this.btn_guardar.onHoverState.IconLeftImage = null;
            this.btn_guardar.onHoverState.IconRightImage = null;
            this.btn_guardar.OnIdleState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(2)))), ((int)(((byte)(56)))), ((int)(((byte)(119)))));
            this.btn_guardar.OnIdleState.BorderRadius = 1;
            this.btn_guardar.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btn_guardar.OnIdleState.BorderThickness = 1;
            this.btn_guardar.OnIdleState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(2)))), ((int)(((byte)(56)))), ((int)(((byte)(119)))));
            this.btn_guardar.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.btn_guardar.OnIdleState.IconLeftImage = null;
            this.btn_guardar.OnIdleState.IconRightImage = null;
            this.btn_guardar.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btn_guardar.OnPressedState.BorderRadius = 1;
            this.btn_guardar.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btn_guardar.OnPressedState.BorderThickness = 1;
            this.btn_guardar.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btn_guardar.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.btn_guardar.OnPressedState.IconLeftImage = null;
            this.btn_guardar.OnPressedState.IconRightImage = null;
            this.btn_guardar.Size = new System.Drawing.Size(260, 144);
            this.btn_guardar.TabIndex = 21;
            this.btn_guardar.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btn_guardar.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btn_guardar.TextMarginLeft = 0;
            this.btn_guardar.TextPadding = new System.Windows.Forms.Padding(0);
            this.btn_guardar.UseDefaultRadiusAndThickness = true;
            this.btn_guardar.Click += new System.EventHandler(this.btn_guardar_Click);
            // 
            // cod_input
            // 
            this.cod_input.AcceptsReturn = false;
            this.cod_input.AcceptsTab = false;
            this.cod_input.AnimationSpeed = 200;
            this.cod_input.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.cod_input.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.cod_input.AutoSizeHeight = true;
            this.cod_input.BackColor = System.Drawing.Color.White;
            this.cod_input.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("cod_input.BackgroundImage")));
            this.cod_input.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.cod_input.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.cod_input.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.cod_input.BorderColorIdle = System.Drawing.Color.Silver;
            this.cod_input.BorderRadius = 1;
            this.cod_input.BorderThickness = 1;
            this.cod_input.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.cod_input.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.cod_input.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.cod_input.DefaultText = "";
            this.cod_input.FillColor = System.Drawing.Color.White;
            this.cod_input.HideSelection = true;
            this.cod_input.IconLeft = null;
            this.cod_input.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.cod_input.IconPadding = 10;
            this.cod_input.IconRight = null;
            this.cod_input.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.cod_input.Lines = new string[0];
            this.cod_input.Location = new System.Drawing.Point(650, 131);
            this.cod_input.MaxLength = 32767;
            this.cod_input.MinimumSize = new System.Drawing.Size(1, 1);
            this.cod_input.Modified = false;
            this.cod_input.Multiline = false;
            this.cod_input.Name = "cod_input";
            stateProperties21.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties21.FillColor = System.Drawing.Color.Empty;
            stateProperties21.ForeColor = System.Drawing.Color.Empty;
            stateProperties21.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.cod_input.OnActiveState = stateProperties21;
            stateProperties22.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties22.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties22.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties22.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.cod_input.OnDisabledState = stateProperties22;
            stateProperties23.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties23.FillColor = System.Drawing.Color.Empty;
            stateProperties23.ForeColor = System.Drawing.Color.Empty;
            stateProperties23.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.cod_input.OnHoverState = stateProperties23;
            stateProperties24.BorderColor = System.Drawing.Color.Silver;
            stateProperties24.FillColor = System.Drawing.Color.White;
            stateProperties24.ForeColor = System.Drawing.Color.Empty;
            stateProperties24.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.cod_input.OnIdleState = stateProperties24;
            this.cod_input.Padding = new System.Windows.Forms.Padding(3);
            this.cod_input.PasswordChar = '\0';
            this.cod_input.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.cod_input.PlaceholderText = "codigo";
            this.cod_input.ReadOnly = false;
            this.cod_input.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.cod_input.SelectedText = "";
            this.cod_input.SelectionLength = 0;
            this.cod_input.SelectionStart = 0;
            this.cod_input.ShortcutsEnabled = true;
            this.cod_input.Size = new System.Drawing.Size(260, 39);
            this.cod_input.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Material;
            this.cod_input.TabIndex = 22;
            this.cod_input.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.cod_input.TextMarginBottom = 0;
            this.cod_input.TextMarginLeft = 3;
            this.cod_input.TextMarginTop = 1;
            this.cod_input.TextPlaceholder = "codigo";
            this.cod_input.UseSystemPasswordChar = false;
            this.cod_input.WordWrap = true;
            // 
            // nombre_input
            // 
            this.nombre_input.AcceptsReturn = false;
            this.nombre_input.AcceptsTab = false;
            this.nombre_input.AnimationSpeed = 200;
            this.nombre_input.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.nombre_input.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.nombre_input.AutoSizeHeight = true;
            this.nombre_input.BackColor = System.Drawing.Color.White;
            this.nombre_input.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("nombre_input.BackgroundImage")));
            this.nombre_input.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.nombre_input.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.nombre_input.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.nombre_input.BorderColorIdle = System.Drawing.Color.Silver;
            this.nombre_input.BorderRadius = 1;
            this.nombre_input.BorderThickness = 1;
            this.nombre_input.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.nombre_input.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.nombre_input.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.nombre_input.DefaultText = "";
            this.nombre_input.FillColor = System.Drawing.Color.White;
            this.nombre_input.HideSelection = true;
            this.nombre_input.IconLeft = null;
            this.nombre_input.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.nombre_input.IconPadding = 10;
            this.nombre_input.IconRight = null;
            this.nombre_input.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.nombre_input.Lines = new string[0];
            this.nombre_input.Location = new System.Drawing.Point(650, 176);
            this.nombre_input.MaxLength = 32767;
            this.nombre_input.MinimumSize = new System.Drawing.Size(1, 1);
            this.nombre_input.Modified = false;
            this.nombre_input.Multiline = false;
            this.nombre_input.Name = "nombre_input";
            stateProperties25.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties25.FillColor = System.Drawing.Color.Empty;
            stateProperties25.ForeColor = System.Drawing.Color.Empty;
            stateProperties25.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.nombre_input.OnActiveState = stateProperties25;
            stateProperties26.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties26.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties26.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties26.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.nombre_input.OnDisabledState = stateProperties26;
            stateProperties27.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties27.FillColor = System.Drawing.Color.Empty;
            stateProperties27.ForeColor = System.Drawing.Color.Empty;
            stateProperties27.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.nombre_input.OnHoverState = stateProperties27;
            stateProperties28.BorderColor = System.Drawing.Color.Silver;
            stateProperties28.FillColor = System.Drawing.Color.White;
            stateProperties28.ForeColor = System.Drawing.Color.Empty;
            stateProperties28.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.nombre_input.OnIdleState = stateProperties28;
            this.nombre_input.Padding = new System.Windows.Forms.Padding(3);
            this.nombre_input.PasswordChar = '\0';
            this.nombre_input.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.nombre_input.PlaceholderText = "Nombre";
            this.nombre_input.ReadOnly = false;
            this.nombre_input.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.nombre_input.SelectedText = "";
            this.nombre_input.SelectionLength = 0;
            this.nombre_input.SelectionStart = 0;
            this.nombre_input.ShortcutsEnabled = true;
            this.nombre_input.Size = new System.Drawing.Size(260, 39);
            this.nombre_input.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Material;
            this.nombre_input.TabIndex = 23;
            this.nombre_input.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.nombre_input.TextMarginBottom = 0;
            this.nombre_input.TextMarginLeft = 3;
            this.nombre_input.TextMarginTop = 1;
            this.nombre_input.TextPlaceholder = "Nombre";
            this.nombre_input.UseSystemPasswordChar = false;
            this.nombre_input.WordWrap = true;
            // 
            // USER_FORM
            // 
            this.AutoScaleDimensions = new System.Drawing.SizeF(6F, 13F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.ClientSize = new System.Drawing.Size(922, 596);
            this.Controls.Add(this.date);
            this.Controls.Add(this.Contra_input);
            this.Controls.Add(this.Usuario_input);
            this.Controls.Add(this.Tipo_usuario_input);
            this.Controls.Add(this.Apellido_input);
            this.Controls.Add(this.nombre_input);
            this.Controls.Add(this.cod_input);
            this.Controls.Add(this.btn_guardar);
            this.Controls.Add(this.btn_eliminar);
            this.Controls.Add(this.btn_editar);
            this.Controls.Add(this.btn_nuevo);
            this.Controls.Add(this.tabla);
            this.Controls.Add(this.bunifuPictureBox2);
            this.Controls.Add(this.buscar);
            this.Controls.Add(this.bunifuPanel1);
            this.FormBorderStyle = System.Windows.Forms.FormBorderStyle.None;
            this.Name = "USER_FORM";
            this.StartPosition = System.Windows.Forms.FormStartPosition.CenterScreen;
            this.Text = "USER_FORM";
            this.Load += new System.EventHandler(this.USER_FORM_Load);
            ((System.ComponentModel.ISupportInitialize)(this.tabla)).EndInit();
            this.bunifuPanel1.ResumeLayout(false);
            this.bunifuPanel1.PerformLayout();
            ((System.ComponentModel.ISupportInitialize)(this.bunifuPictureBox2)).EndInit();
            this.ResumeLayout(false);

        }

        #endregion
        private Bunifu.UI.WinForms.BunifuDataGridView tabla;
        private Bunifu.UI.WinForms.BunifuDatePicker date;
        private Bunifu.UI.WinForms.BunifuTextBox Contra_input;
        private Bunifu.UI.WinForms.BunifuTextBox Tipo_usuario_input;
        private Bunifu.UI.WinForms.BunifuTextBox Usuario_input;
        private Bunifu.UI.WinForms.BunifuPanel bunifuPanel1;
        private Bunifu.UI.WinForms.BunifuLabel bunifuLabel1;
        private Bunifu.UI.WinForms.BunifuTextBox Apellido_input;
        private Bunifu.UI.WinForms.BunifuTextBox buscar;
        private Bunifu.UI.WinForms.BunifuPictureBox bunifuPictureBox2;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton btn_nuevo;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton btn_editar;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton btn_eliminar;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton btn_guardar;
        private Bunifu.UI.WinForms.BunifuTextBox cod_input;
        private Bunifu.UI.WinForms.BunifuTextBox nombre_input;
    }
}